export const RouteNames = {
  CHANNELS: 'CHANNELS',
  CHANNEL: 'CHANNEL',
  USERS: 'USERS',
  USER: 'USER',
  COMMUNITY_LIBRARY_SUBMISSION: 'COMMUNITY_LIBRARY_SUBMISSION',
};

export const rowsPerPageItems = [25, 50, 75, 100];
