steps:
- name: 'gcr.io/cloud-builders/docker'
  id: pull-app-image-cache
  args: ['pull', 'gcr.io/$PROJECT_ID/learningequality-studio-app:latest']

- name: 'gcr.io/cloud-builders/docker'
  id: build-app-image
  entrypoint: bash
  waitFor: ['pull-app-image-cache']              # wait for app image cache pull to finish
  args:
  - -c
  - >
    docker build
    --build_arg COMMIT_SHA=$COMMIT_SHA
    -f docker/prod/app/Dockerfile
    --cache-from gcr.io/$PROJECT_ID/learningequality-studio-app:latest
    -t gcr.io/$PROJECT_ID/learningequality-studio-app:$COMMIT_SHA
    -t gcr.io/$PROJECT_ID/learningequality-studio-app:latest
    .

- name: 'gcr.io/cloud-builders/docker'
  id: build-nginx-image
  waitFor: ['-']              # don't wait for previous steps
  args: [
    'build',
    '-f', 'docker/prod/nginx/Dockerfile',
    '--cache-from', 'gcr.io/$PROJECT_ID/learningequality-studio-nginx:latest',
    '-t', 'gcr.io/$PROJECT_ID/learningequality-studio-nginx:$COMMIT_SHA',
    '-t', 'gcr.io/$PROJECT_ID/learningequality-studio-nginx:latest',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: pull-prober-image-cache
  waitFor: ['-']
  args: ['pull', 'gcr.io/$PROJECT_ID/learningequality-studio-prober:latest']

- name: 'gcr.io/cloud-builders/docker'
  id: build-prober-image
  waitFor: ['pull-prober-image-cache']              # don't wait for previous steps
  args: [
    'build',
    '-f', 'docker/prod/prober/Dockerfile',
    '--cache-from', 'gcr.io/$PROJECT_ID/learningequality-studio-prober:latest',
    '-t', 'gcr.io/$PROJECT_ID/learningequality-studio-prober:$COMMIT_SHA',
    '-t', 'gcr.io/$PROJECT_ID/learningequality-studio-prober:latest',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: push-app-image
  waitFor: ['build-app-image']
  args: ['push', 'gcr.io/$PROJECT_ID/learningequality-studio-app:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  id: push-nginx-image
  waitFor: ['build-nginx-image']
  args: ['push', 'gcr.io/$PROJECT_ID/learningequality-studio-nginx:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  id: push-prober-image
  waitFor: ['build-prober-image']
  args: ['push', 'gcr.io/$PROJECT_ID/learningequality-studio-prober:$COMMIT_SHA']

- name: 'gcr.io/$PROJECT_ID/helm'
  id: helm-deploy-studio-instance
  waitFor: ['push-app-image', 'push-nginx-image']
  dir: "k8s"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-f'
  - 'CLOUDSDK_CONTAINER_CLUSTER=contentworkshop-central'
  entrypoint: 'bash'
  args:
    - -c
    - >
      /builder/helm.bash &&
      ./helm-deploy.sh
      $BRANCH_NAME
      gcr.io/$PROJECT_ID/learningequality-studio-app:$COMMIT_SHA
      gcr.io/$PROJECT_ID/learningequality-studio-nginx:$COMMIT_SHA
      $_STORAGE_BUCKET
      $COMMIT_SHA
      $PROJECT_ID
      $_DATABASE_INSTANCE_NAME
      us-central1


substitutions:
  _DATABASE_INSTANCE_NAME: develop  # by default, connect to the develop DB
  _STORAGE_BUCKET: develop-studio-content

timeout: 3600s
images:
  - gcr.io/$PROJECT_ID/learningequality-studio-nginx:latest
  - gcr.io/$PROJECT_ID/learningequality-studio-nginx:$COMMIT_SHA
  - gcr.io/$PROJECT_ID/learningequality-studio-app:latest
  - gcr.io/$PROJECT_ID/learningequality-studio-app:$COMMIT_SHA
  - 'gcr.io/$PROJECT_ID/learningequality-studio-prober:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/learningequality-studio-prober:latest'
