project_identifier: content-curation
api_key: <API key>
base_path: .

files:
  - source: "/contentcuration/locale/en/LC_FRONTEND_MESSAGES/*.json"
    translation: "/contentcuration/locale/%locale_with_underscore%/LC_FRONTEND_MESSAGES/%original_file_name%"

  - source: "/contentcuration/locale/en/LC_MESSAGES/*.po"
    translation: "/contentcuration/locale/%locale_with_underscore%/LC_MESSAGES/%original_file_name%"
