FROM ubuntu:xenial

RUN apt-get update

RUN apt-get -y install curl

# install node
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -

RUN apt-get -y install nodejs python python-dev \
    python-pip gcc libpq-dev ffmpeg imagemagick \
    ghostscript python-tk make libjpeg-dev \
    wkhtmltopdf

RUN npm install -g yarn

EXPOSE 8080

RUN pip install pipenv
# pip 18.1 gives an error with pipenv, so pin the version to 18.0 until there is a fix.
# More info here: https://github.com/pypa/pipenv/issues/2924
RUN pip install pip==18.0

# Where the host source code will be mounted when run under docker compose
RUN mkdir /src
WORKDIR /src

ENTRYPOINT ["pipenv", "run", "python", "deploy/entrypoint.py"]
CMD ["make", "devserver"]
