# minimum number of minutes
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - kolibri-build
  - kolibri-constants
  - kolibri-design-system
  - kolibri-format
  - kolibri-glob
  - kolibri-i18n
  - kolibri-logging
