#!/bin/bash

echo "
DROP DATABASE IF EXISTS \"$POSTGRES_DB\";

DROP ROLE IF EXISTS \"$POSTGRES_USER\";

CREATE USER $POSTGRES_USER
  WITH NOSUPERUSER INHERIT NOCREATEROLE CREATEDB LOGIN NOREPLICATION NOBYPASSRLS
  PASSWORD '$POSTGRES_PASSWORD'
;

CREATE DATABASE \"$POSTGRES_DB\"
  WITH TEMPLATE = template0
  ENCODING = 'UTF8'
  OWNER = '$POSTGRES_USER'
;
" > /tmp/postgres_init.sql

su postgres -c 'psql -f /tmp/postgres_init.sql'
