# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-20 17:34
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0001_squashed_0094_auto_20180910_2342"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="thumbnail_encoding_json",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
