# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='readable_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
