# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 19:08
from __future__ import unicode_literals

import contentcuration.models
from django.db import migrations
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contentnode',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='contentnode',
            name='id',
            field=contentcuration.models.UUIDField(default=uuid.uuid4, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=contentcuration.models.UUIDField(default=uuid.uuid4, max_length=32, primary_key=True, serialize=False),
        ),
    ]
