# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 21:31
from __future__ import unicode_literals

import uuid

from django.db import migrations
from django.db import models

import contentcuration.models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0001_squashed_0094_auto_20180910_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTreeNode',
            fields=[
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('id', contentcuration.models.UUIDField(default=uuid.uuid4, max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
