# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0002_language_readable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clipboard_tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_clipboard', to='contentcuration.ContentNode'),
        ),
    ]
