# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0002_channelset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelset',
            name='channels',
        ),
    ]
