# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0003_user_clipboard_tree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentnode',
            old_name='license_owner',
            new_name='copyright_holder',
        ),
    ]
