# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-20 17:34
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0003_copy_data"),
    ]

    operations = [
        migrations.RemoveField(model_name="channel", name="thumbnail_encoding"),
        migrations.RenameField(
            model_name="channel",
            old_name="thumbnail_encoding_json",
            new_name="thumbnail_encoding",
        ),
    ]
