# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0004_auto_20160413_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
