# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0004_auto_20160720_1220'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contentnode',
            managers=[
            ],
        ),
    ]
