# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0005_auto_20160816_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
