# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0006_remove_topictree_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topictree',
            name='name',
            field=models.CharField(default=b'tree', help_text='Displayed to the user', max_length=255, verbose_name='topic tree name'),
        ),
    ]
