# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0005_formatpreset_thumbnail'),
        ('contentcuration', '0006_contentnode_published'),
    ]

    operations = [
    ]
