# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0008_channel_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='published',
        ),
    ]
