# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0011_file_source_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='source_url',
        ),
    ]
