# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0011_file_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='staging_tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_staging', to='contentcuration.ContentNode'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='Users with edit rights', related_name='editable_channels', to=settings.AUTH_USER_MODEL, verbose_name='editors'),
        ),
        migrations.AlterField(
            model_name='contentkind',
            name='kind',
            field=models.CharField(choices=[(b'topic', 'Topic'), (b'video', 'Video'), (b'audio', 'Audio'), (b'exercise', 'Exercise'), (b'document', 'Document')], max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fileformat',
            name='extension',
            field=models.CharField(choices=[(b'mp4', 'mp4'), (b'vtt', 'vtt'), (b'srt', 'srt'), (b'mp3', 'mp3'), (b'wav', 'wav'), (b'pdf', 'pdf'), (b'jpg', 'jpg'), (b'jpeg', 'jpeg'), (b'png', 'png'), (b'perseus', 'perseus')], max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formatpreset',
            name='id',
            field=models.CharField(choices=[(b'high_res_video', 'High resolution video'), (b'low_res_video', 'Low resolution video'), (b'vector_video', 'Vector video'), (b'video_thumbnail', 'Thumbnail'), (b'video_subtitle', 'Subtitle'), (b'aud', 'Audio'), (b'audio_thumbnail', 'Thumbnail'), (b'doc', 'Document'), (b'document_thumbnail', 'Thumbnail'), (b'exercise', 'Exercise'), (b'exercise_thumbnail', 'Thumbnail')], max_length=150, primary_key=True, serialize=False),
        ),
    ]
