# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 21:44
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0011_file_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='staging_tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='channel_staging', to='contentcuration.ContentNode'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='Users with edit rights', related_name='editable_channels',
                                         to=settings.AUTH_USER_MODEL, verbose_name='editors'),
        ),
        migrations.AlterField(
            model_name='contentkind',
            name='kind',
            field=models.CharField(choices=[('topic', 'Topic'), ('video', 'Video'), ('audio', 'Audio'), ('exercise',
                                                                                                            'Exercise'), ('document', 'Document')], max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fileformat',
            name='extension',
            field=models.CharField(choices=[('mp4', 'mp4'), ('vtt', 'vtt'), ('srt', 'srt'), ('mp3', 'mp3'), ('wav', 'wav'), ('pdf', 'pdf'),
                                            ('jpg', 'jpg'), ('jpeg', 'jpeg'), ('png', 'png'), ('perseus', 'perseus')], max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formatpreset',
            name='id',
            field=models.CharField(choices=[('high_res_video', 'High resolution video'), ('low_res_video', 'Low resolution video'), ('vector_video', 'Vector video'), ('video_thumbnail', 'Thumbnail'), ('video_subtitle', 'Subtitle'), (
                'aud', 'Audio'), ('audio_thumbnail', 'Thumbnail'), ('doc', 'Document'), ('document_thumbnail', 'Thumbnail'), ('exercise', 'Exercise'), ('exercise_thumbnail', 'Thumbnail')], max_length=150, primary_key=True, serialize=False),
        ),
    ]
