# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 22:06
from __future__ import unicode_literals

import contentcuration.models
from django.db import migrations
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0012_auto_20160907_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='node_id',
            field=contentcuration.models.UUIDField(default=uuid.uuid4, editable=False, max_length=32),
        ),
    ]
