# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0013_contentnode_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_language', to='contentcuration.Language'),
        ),
    ]
