# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0014_channel_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentitem',
            name='exercise',
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='contentnode',
            field=models.ForeignKey(default='5451535d4e6341acba2c4261471b7c1f', on_delete=django.db.models.deletion.CASCADE, related_name='assessment_items', to='contentcuration.ContentNode'),
            preserve_default=False,
        ),
    ]
