# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0014_channel_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
