# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0016_auto_20160915_1206'),
        ('contentcuration', '0014_file_source_url'),
    ]

    operations = [
    ]
