# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0016_auto_20160915_1206'),
        ('contentcuration', '0015_auto_20160916_1349'),
    ]

    operations = [
    ]
