# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0017_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentitem',
            name='contentnode',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='title',
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_assessment_items', to='contentcuration.Exercise'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='contentnode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='contentcuration.ContentNode'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='mastery_model',
            field=models.CharField(default='do-all', max_length=200),
        ),
    ]
