# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 23:20
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0020_auto_20160919_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentitem',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='all_assessment_items', to='contentcuration.Exercise'),
        ),
    ]
