# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0021_auto_20160919_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentitem',
            name='exercise',
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='contentnode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_items', to='contentcuration.ContentNode'),
        ),
    ]
