# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0023_contentnode_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentitem',
            name='help_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
