# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0025_auto_20160921_1356'),
    ]

    operations = [
    ]
