# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 22:27
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0027_auto_20160926_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='mastery_model',
            field=models.CharField(choices=[(b'do_all', b'Do all'), (b'num_correct_in_a_row_10', b'10 in a row'), (b'num_correct_in_a_row_3',
                                                                                                                   b'3 in a row'), (b'num_correct_in_a_row_5', b'5 in a row'), (b'skill_check', b'Skill check')], default=b'do_all', max_length=200),
        ),
        migrations.AlterField(
            model_name='formatpreset',
            name='id',
            field=models.CharField(choices=[(b'high_res_video', b'High resolution video'), (b'low_res_video', b'Low resolution video'), (b'vector_video', b'Vector video'), (b'video_thumbnail', b'Thumbnail'), (b'video_subtitle', b'Subtitle'), (
                b'audio', b'Audio'), (b'audio_thumbnail', b'Thumbnail'), (b'document', b'Document'), (b'document_thumbnail', b'Thumbnail'), (b'exercise', b'Exercise'), (b'exercise_thumbnail', b'Thumbnail')], max_length=150, primary_key=True, serialize=False),
        ),
    ]
