# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0028_auto_20160926_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatpreset',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='formatpreset',
            name='kind',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='format_presets', to='contentcuration.ContentKind'),
        ),
    ]
