# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0030_auto_20161005_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentitem',
            name='raw_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='formatpreset',
            name='id',
            field=models.CharField(choices=[(b'high_res_video', b'High Resolution'), (b'low_res_video', b'Low Resolution'), (b'vector_video', b'Vectorized'), (b'video_thumbnail', b'Thumbnail'), (b'video_subtitle', b'Subtitle'), (b'audio', b'Audio'), (b'audio_thumbnail', b'Thumbnail'), (b'document', b'Document'), (b'document_thumbnail', b'Thumbnail'), (b'exercise', b'Exercise'), (b'exercise_thumbnail', b'Thumbnail')], max_length=150, primary_key=True, serialize=False),
        ),
    ]
