# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0032_auto_20161010_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentitem',
            name='hint',
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='hints',
            field=models.TextField(default='[]'),
        ),
    ]
