# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 22:09
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0033_auto_20161012_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='mastery_model',
            field=models.CharField(choices=[(b'do_all', b'Do all'), (b'num_correct_in_a_row_10', b'10 in a row'), (b'num_correct_in_a_row_3', b'3 in a row'), (
                b'num_correct_in_a_row_5', b'5 in a row'), (b'skill_check', b'Skill check'), (b'm_of_n', b'M out of N')], default=b'do_all', max_length=200),
        ),
        migrations.AlterField(
            model_name='fileformat',
            name='extension',
            field=models.CharField(choices=[(b'mp4', b'mp4'), (b'vtt', b'vtt'), (b'srt', b'srt'), (b'mp3', b'mp3'), (b'wav', b'wav'), (b'pdf', b'pdf'), (b'jpg', b'jpg'), (
                b'jpeg', b'jpeg'), (b'png', b'png'), (b'json', b'json'), (b'svg', b'svg'), (b'perseus', b'perseus')], max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formatpreset',
            name='id',
            field=models.CharField(choices=[(b'high_res_video', b'High Resolution'), (b'low_res_video', b'Low Resolution'), (b'vector_video', b'Vectorized'), (b'video_thumbnail', b'Thumbnail'), (b'video_subtitle', b'Subtitle'), (b'audio', b'Audio'), (b'audio_thumbnail', b'Thumbnail'), (
                b'document', b'Document'), (b'document_thumbnail', b'Thumbnail'), (b'exercise', b'Exercise'), (b'exercise_thumbnail', b'Thumbnail'), (b'exercise_image', b'Exercise Image'), (b'exercise_graphie', b'Exercise Graphie')], max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formatpreset',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
