# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0034_auto_20161014_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='source_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
