# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0035_auto_20161018_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnode',
            name='author',
            field=models.CharField(blank=True, help_text='Person who created content', max_length=200, null=True),
        ),
    ]
