# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0036_auto_20161018_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentnode',
            name='author',
        ),
    ]
