# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0037_remove_contentnode_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='author',
            field=models.CharField(blank=True, help_text='Person who created content', max_length=200, null=True),
        ),
    ]
