# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 00:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0040_file_assessment_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='previous_tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='channel_previous', to='contentcuration.ContentNode'),
        ),
    ]
