# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-06 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0042_auto_20170105_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='lang',
            new_name='language',
        ),
        migrations.AddField(
            model_name='formatpreset',
            name='subtitle',
            field=models.BooleanField(default=False),
        ),
    ]
