# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0042_auto_20161202_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='native_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_subcode',
            field=models.CharField(db_index=True, max_length=2, null=True),
        ),
    ]
