# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0042_auto_20161206_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='viewers',
            field=models.ManyToManyField(blank=True, help_text='Users with view only rights', related_name='view_only_channels',
                                         to=settings.AUTH_USER_MODEL, verbose_name='viewers'),
        ),
    ]
