# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0042_auto_20161202_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
