# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-13 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0042_auto_20161130_1446'),
        ('contentcuration', '0042_auto_20161205_1622'),
    ]

    operations = [
    ]
