# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0043_auto_20170106_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='contentcuration.Language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_subcode',
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
    ]
