# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0042_auto_20161205_1622'),
        ('contentcuration', '0043_channel_viewers'),
    ]

    operations = [
    ]
