# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-14 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0043_merge'),
        ('contentcuration', '0044_auto_20170109_1443'),
    ]

    operations = [
    ]
