# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0044_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='viewonly',
            field=models.BooleanField(default=False),
        ),
    ]
