# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0045_invitation_viewonly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='viewonly',
        ),
        migrations.AddField(
            model_name='invitation',
            name='share_mode',
            field=models.CharField(default='edit', max_length=50),
        ),
    ]
