# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-20 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0046_auto_20161222_1210'),
        ('contentcuration', '0045_merge'),
        ('contentcuration', '0045_auto_20170119_1429'),
    ]

    operations = [
    ]
