# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-20 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0046_auto_20161222_1210'),
    ]

    operations = [
    ]
