# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-20 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0048_auto_20170119_1732'),
        ('contentcuration', '0045_auto_20170119_1429'),
    ]

    operations = [
    ]
