# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-23 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0049_merge'),
        ('contentcuration', '0043_auto_20170106_1359'),
    ]

    operations = [
    ]
