# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-25 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0049_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='lang',
            new_name='language',
        ),
        migrations.AlterField(
            model_name='contentnode',
            name='author',
            field=models.CharField(blank=True, default='', help_text='Person who created content', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contentnode',
            name='copyright_holder',
            field=models.CharField(blank=True, default='', help_text='Organization of person who holds the essential rights', max_length=200),
        ),
    ]
