# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 00:33
from __future__ import unicode_literals

import contentcuration.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0050_auto_20170125_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='original_source_node_id',
            field=contentcuration.models.UUIDField(editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='contentnode',
            name='source_node_id',
            field=contentcuration.models.UUIDField(editable=False, max_length=32, null=True),
        ),
    ]
