# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-26 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0050_auto_20170125_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='native_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='contentcuration.Language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_code',
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_subcode',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='readable_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
