# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0051_auto_20170123_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnode',
            name='copyright_holder',
            field=models.CharField(blank=True, help_text='Organization of person who holds the essential rights', max_length=200, null=True),
        ),
    ]
