# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0051_auto_20170126_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='ricecooker_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='source_domain',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='source_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contentnode',
            name='source_domain',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contentnode',
            name='source_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
