# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0052_auto_20170123_1619'),
        ('contentcuration', '0045_merge'),
    ]

    operations = [
    ]
