# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-07 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0051_auto_20170126_1012'),
        ('contentcuration', '0052_auto_20170201_1155'),
    ]

    operations = [
    ]
