# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0053_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lang_subcode',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
    ]
