# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-09 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0054_language_native_name'),
        ('contentcuration', '0052_auto_20170130_0931'),
    ]

    operations = [
    ]
