# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-16 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0055_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentitem',
            name='randomize',
            field=models.BooleanField(default=False),
        ),
    ]
