# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-17 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0056_assessmentitem_randomize'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentitem',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
