# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-29 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0058_auto_20170223_1636'),
        ('contentcuration', '0057_assessmentitem_deleted'),
    ]

    operations = [
    ]
