# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-03 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0059_auto_20170402_1504'),
        ('contentcuration', '0059_merge'),
    ]

    operations = [
    ]
