# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-27 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0057_assessmentitem_deleted'),
        ('contentcuration', '0059_channelresourcesize'),
    ]

    operations = [
    ]
