# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-06 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0059_merge'),
        ('contentcuration', '0061_auto_20170327_1344'),
    ]

    operations = [
    ]
