# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-11 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0063_auto_20170411_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnode',
            name='copyright_holder',
            field=models.CharField(blank=True, default='', help_text='Organization of person who holds the essential rights', max_length=200, null=True),
        ),
    ]
