# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-24 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0068_auto_20170519_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='preferences',
            field=models.TextField(default='{"auto_derive_video_thumbnail": true, "auto_randomize_questions": true, "copyright_holder": null, "auto_derive_document_thumbnail": true, "license_description": null, "mastery_model": "num_correct_in_a_row_5", "m_value": 5, "license": "CC BY", "language": null, "author": null, "auto_derive_exercise_thumbnail": true, "auto_derive_html5_thumbnail": true, "auto_derive_audio_thumbnail": true, "n_value": 5}'),
        ),
    ]
