# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-11 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0069_channel_preferences'),
        ('contentcuration', '0068_auto_20170509_1456'),
    ]

    operations = [
    ]
