# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-23 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0070_merge'),
        ('contentcuration', '0069_auto_20170605_2122'),
    ]

    operations = [
    ]
