# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-27 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0071_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_language', to='contentcuration.Language'),
        ),
    ]
