# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-31 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0071_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='secret_tokens',
            field=models.ManyToManyField(blank=True, related_name='channels', to='contentcuration.SecretToken', verbose_name='secret tokens'),
        ),
    ]
