# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-18 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0072_auto_20170731_2153'),
        ('contentcuration', '0072_contentnode_language'),
    ]

    operations = [
    ]
