# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-12 01:37
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0072_contentnode_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=400)),
                ('file_size', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='disk_space',
            field=models.IntegerField(default=524288000, help_text='How many bytes a user can upload'),
        ),
        migrations.AddField(
            model_name='stagedfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='staged_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
