# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-09 22:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0073_auto_20170801_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=400)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staged_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
