# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-21 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0073_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
