# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-25 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0073_auto_20170911_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='preferences',
            field=models.TextField(default=b'{"auto_derive_video_thumbnail": true, "auto_randomize_questions": true, "copyright_holder": null, "auto_derive_document_thumbnail": true, "license_description": null, "mastery_model": "num_correct_in_a_row_5", "m_value": 5, "license": null, "language": null, "author": null, "auto_derive_exercise_thumbnail": true, "auto_derive_html5_thumbnail": true, "auto_derive_audio_thumbnail": true, "n_value": 5}'),
        ),
        migrations.AlterField(
            model_name='contentnode',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contentcuration.License'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.TextField(default=b'{"auto_derive_video_thumbnail": true, "auto_randomize_questions": true, "copyright_holder": null, "auto_derive_document_thumbnail": true, "license_description": null, "mastery_model": "num_correct_in_a_row_5", "m_value": 5, "license": null, "language": null, "author": null, "auto_derive_exercise_thumbnail": true, "auto_derive_html5_thumbnail": true, "auto_derive_audio_thumbnail": true, "n_value": 5}'),
        ),
    ]
