# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-03 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0074_auto_20170925_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='freeze_authoring_data',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='license',
            name='copyright_holder_required',
            field=models.BooleanField(default=True),
        ),
    ]
