# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-18 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0075_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='priority',
            field=models.IntegerField(default=0, help_text='Order to display public channels'),
        ),
    ]
