# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-03 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0074_auto_20170925_1144'),
        ('contentcuration', '0075_merge'),
    ]

    operations = [
    ]
