# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-10 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0076_auto_20171003_1847'),
        ('contentcuration', '0076_auto_20170927_1817'),
    ]

    operations = [
    ]
