# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-04 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0076_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='freeze_authoring_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='license',
            name='copyright_holder_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='priority',
            field=models.IntegerField(default=0, help_text='Order to display public channels'),
        ),
        migrations.AlterField(
            model_name='user',
            name='disk_space',
            field=models.FloatField(default=524288000, help_text='How many bytes a user can upload'),
        ),
    ]
