# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-19 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0076_auto_20170918_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disk_space',
            field=models.FloatField(default=524288000, help_text='How many bytes a user can upload'),
        ),
    ]
