# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-14 19:18
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0079_contentnode_publishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='information',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
