# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-15 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0080_auto_20180314_1756'),
        ('contentcuration', '0081_auto_20180314_1631'),
    ]

    operations = [
    ]
