# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-27 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0082_merge'),
        ('contentcuration', '0079_auto_20180326_1448'),
    ]

    operations = [
    ]
