# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-16 23:38
from __future__ import unicode_literals

import contentcuration.models
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0084_auto_20180329_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='policies',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_on_disk',
            field=models.FileField(blank=True, max_length=500, upload_to=contentcuration.models.object_storage_name),
        ),
    ]
