# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-18 19:21
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0084_auto_20180329_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='policies',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
