# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-06 00:14
from __future__ import unicode_literals

import jsonfield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0084_auto_20180329_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='aggregator',
            field=models.CharField(blank=True, help_text='Who gathered this content together?', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contentnode',
            name='provider',
            field=models.CharField(blank=True, help_text='Who distributed this content?', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='content_defaults',
            field=jsonfield.fields.JSONField(default={b'aggregator': None, 'author': None, 'auto_derive_audio_thumbnail': True, 'auto_derive_document_thumbnail': True, 'auto_derive_exercise_thumbnail': True, 'auto_derive_html5_thumbnail': True,
                                                      'auto_derive_video_thumbnail': True, 'auto_randomize_questions': True, 'copyright_holder': None, 'language': None, 'license': None, 'license_description': None, 'm_value': 5, 'mastery_model': 'num_correct_in_a_row_5', 'n_value': 5, 'provider': None}),
        ),
        migrations.AlterField(
            model_name='channel',
            name='preferences',
            field=models.TextField(default='{"auto_derive_exercise_thumbnail": true, "auto_derive_video_thumbnail": true, "m_value": 5, "language": null, "license": null, "author": null, "aggregator": null, "auto_randomize_questions": true, "auto_derive_document_thumbnail": true, "copyright_holder": null, "auto_derive_html5_thumbnail": true, "provider": null, "auto_derive_audio_thumbnail": true, "license_description": null, "n_value": 5, "mastery_model": "num_correct_in_a_row_5"}'),
        ),
        migrations.AlterField(
            model_name='contentnode',
            name='author',
            field=models.CharField(blank=True, default='', help_text='Who created this content?', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='content_defaults',
            field=jsonfield.fields.JSONField(default={b'aggregator': None, 'author': None, 'auto_derive_audio_thumbnail': True, 'auto_derive_document_thumbnail': True, 'auto_derive_exercise_thumbnail': True, 'auto_derive_html5_thumbnail': True,
                                                      'auto_derive_video_thumbnail': True, 'auto_randomize_questions': True, 'copyright_holder': None, 'language': None, 'license': None, 'license_description': None, 'm_value': 5, 'mastery_model': 'num_correct_in_a_row_5', 'n_value': 5, 'provider': None}),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.TextField(default='{"auto_derive_exercise_thumbnail": true, "auto_derive_video_thumbnail": true, "m_value": 5, "language": null, "license": null, "author": null, "aggregator": null, "auto_randomize_questions": true, "auto_derive_document_thumbnail": true, "copyright_holder": null, "auto_derive_html5_thumbnail": true, "provider": null, "auto_derive_audio_thumbnail": true, "license_description": null, "n_value": 5, "mastery_model": "num_correct_in_a_row_5"}'),
        ),
    ]
