# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-02 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0086_auto_20180626_1055'),
        ('contentcuration', '0085_auto_20180605_1714'),
    ]

    operations = [
    ]
