# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-05 20:07
from __future__ import unicode_literals

import contentcuration.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0087_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='policies',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
