# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-06 22:42
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0088_auto_20180705_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnode',
            name='aggregator',
            field=models.CharField(blank=True, default='', help_text='Who gathered this content together?', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contentnode',
            name='provider',
            field=models.CharField(blank=True, default='', help_text='Who distributed this content?', max_length=200, null=True),
        ),
    ]
