# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-03 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0089_auto_20180712_1043'),
        ('contentcuration', '0092_auto_20180731_1024'),
    ]

    operations = [
    ]
