# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-03 22:10
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import contentcuration.models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0094_auto_20180910_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSet',
            fields=[
                ('id', contentcuration.models.UUIDField(default=uuid.uuid4, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('public', models.BooleanField(db_index=True, default=False)),
                ('editors', models.ManyToManyField(blank=True, help_text='Users with edit rights', related_name='channel_sets', to=settings.AUTH_USER_MODEL, verbose_name='editors')),
                ('secret_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_sets', to='contentcuration.SecretToken')),
            ],
        ),
    ]
