# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-11 02:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0098_auto_20190424_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='changed_staging_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
