# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 15:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0098_auto_20190412_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshowslide',
            name='caption',
        ),
        migrations.AddField(
            model_name='slideshowslide',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
