# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-15 22:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0098_auto_20190424_1709"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenttag",
            name="tag_name",
            field=models.CharField(max_length=50),
        ),
    ]
