# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0098_extra_fields_json_field'),
        ('contentcuration', '0098_auto_20190424_1709'),
    ]

    operations = [
    ]
