# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-12 00:00
from datetime import datetime

from django.db import migrations


included_languages_deploy_date = datetime(2017, 11, 30)


def calculate_included_languages(apps, schema_editor):
    Channel = apps.get_model("contentcuration", "Channel")
    ContentNode = apps.get_model("contentcuration", "ContentNode")
    for channel in Channel.objects.filter(main_tree__isnull=False, last_published__lt=included_languages_deploy_date):
        content_nodes = ContentNode.objects.filter(
            tree_id=channel.main_tree.tree_id,
            published=True,
        )
        # calculate_included_languages
        node_languages = (
            content_nodes.exclude(language=None)
            .order_by("language")
            .values_list("language", flat=True)
            .distinct()
        )
        file_languages = (
            content_nodes.exclude(files__language=None)
            .values_list("files__language", flat=True)
            .distinct()
        )
        channel.included_languages.add(*(list(node_languages) + list(file_languages)))
        channel.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0099_auto_20190715_2201'),
    ]

    operations = [
        migrations.RunPython(calculate_included_languages, migrations.RunPython.noop)
    ]
