# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0098_extra_fields_json_field'),
        ('contentcuration', '0099_calculate_included_languages'),
    ]

    operations = [
    ]
