# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-15 20:27
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0099_calculate_included_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttag',
            name='tag_name',
            field=models.CharField(max_length=50),
        ),
    ]
