# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-04 16:27
import django.contrib.postgres.fields.jsonb
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0101_extra_fields_json_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnode',
            name='extra_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
