# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-03 18:05
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models

import contentcuration.models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0101_extra_fields_json_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', contentcuration.models.UUIDField(default=uuid.uuid4, max_length=32, primary_key=True, serialize=False)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='contentcuration.Channel')),
            ],
        ),
    ]
