# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-05 16:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0102_auto_20190904_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='published_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
