# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-03 18:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0102_auto_20191203_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='contentcuration.Channel'),
        ),
    ]
