# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-03 18:26
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0103_auto_20191203_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='name',
            field=models.CharField(default='Item', max_length=200),
            preserve_default=False,
        ),
    ]
