# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-05 16:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0103_auto_20190905_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='published_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
