# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-03 18:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0104_auto_20191203_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='contentcuration.Language'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
