# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-06 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0103_auto_20190905_0408'),
        ('contentcuration', '0104_auto_20190905_1643'),
    ]

    operations = [
    ]
