# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-02 17:59
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0108_mptt_tree_id_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentnode",
            name="extra_fields",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
