# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-17 19:48
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0109_auto_20191202_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnode',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
