# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-11 22:45
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0109_auto_20191202_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='demo_server_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='channel',
            name='source_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
