# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-13 22:52
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0110_auto_20200511_2245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="demo_server_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="source_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
