# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-13 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0111_auto_20200423_0124'),
        ('contentcuration', '0110_auto_20200511_2245'),
    ]

    operations = [
    ]
