# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-13 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0112_merge_20200513_0049'),
        ('contentcuration', '0111_auto_20200513_2252'),
    ]

    operations = [
    ]
