# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-28 12:49
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0113_channel_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
