# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-06 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0111_auto_20200423_0124'),
        ('contentcuration', '0113_channel_tagline'),
    ]

    operations = [
    ]
