# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-06 20:20
from django.db import migrations
from django.db import models

import contentcuration.models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("contentcuration", "0114_assessment_item_unique_keypair"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="contentnode",
                    index=models.Index(fields=["node_id"], name="node_id_idx"),
                ),
            ],
            database_operations=[
                # operation to run custom SQL command (check the output of `sqlmigrate`
                # to see the auto-generated SQL, edit as needed)
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY "{index_name}" ON "contentcuration_contentnode" ("node_id");'.format(
                        index_name=contentcuration.models.NODE_ID_INDEX_NAME
                    ),
                    reverse_sql='DROP INDEX "{index_name}"'.format(
                        index_name=contentcuration.models.NODE_ID_INDEX_NAME
                    ),
                ),
            ],
        ),
    ]
