# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-28 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0114_contentnode_complete'),
        ('contentcuration', '0115_index_contentnode_node_id_field'),
    ]

    operations = [
    ]
