# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-28 19:55
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0116_merge_20200828_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnode',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
