# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-14 21:59
from django.db import migrations
from django.db import models

import contentcuration.models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("contentcuration", "0116_index_channel_contentnode_file"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="assessmentitem",
                    index=models.Index(
                        fields=["assessment_id"],
                        name=contentcuration.models.ASSESSMENT_ID_INDEX_NAME,
                    ),
                ),
            ],
            database_operations=[
                # operation to run custom SQL command (check the output of `sqlmigrate`
                # to see the auto-generated SQL, edit as needed)
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY "{index_name}" ON "contentcuration_assessmentitem" ("assessment_id");'.format(
                        index_name=contentcuration.models.ASSESSMENT_ID_INDEX_NAME
                    ),
                    reverse_sql='DROP INDEX "{index_name}"'.format(
                        index_name=contentcuration.models.ASSESSMENT_ID_INDEX_NAME
                    ),
                ),
            ],
        ),
    ]
