# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-14 23:12
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0118_relaunch_migrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="channel_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
