# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-28 16:46
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0119_task_channel_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['email'],
                name='contentcura_email_d4d492_idx'
            ),
        ),
    ]
