# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-28 16:46
from __future__ import unicode_literals

from django.db import migrations

import contentcuration.models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0119_task_channel_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=contentcuration.models.UniqueActiveUsername(
                fields=['email'],
                name='contentcura_email_d4d492_idx'
            ),
        ),
    ]
