# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-17 19:12
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0119_auto_20200915_1839'),
    ]

    operations = [

    ]
