# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-17 19:12
from __future__ import unicode_literals

from django.db import migrations
from django.db import models

import contentcuration.models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("contentcuration", "0120_auto_20200917_1912"),
    ]

    operations = [

    ]
