# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-05 20:28
from django.db import migrations
from django.db import models

from contentcuration.models import FILE_MODIFIED_DESC_INDEX_NAME


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("contentcuration", "0121_auto_20210305_2028"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="file",
                    index=models.Index(
                        fields=["-modified"], name=FILE_MODIFIED_DESC_INDEX_NAME
                    ),
                ),
            ],
            database_operations=[
                # operation to run custom SQL command (check the output of `sqlmigrate`
                # to see the auto-generated SQL, edit as needed)
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY "{index_name}" ON "contentcuration_file"("modified" DESC NULLS LAST)'.format(
                        index_name=FILE_MODIFIED_DESC_INDEX_NAME
                    ),
                    reverse_sql='DROP INDEX "{index_name}"'.format(
                        index_name=FILE_MODIFIED_DESC_INDEX_NAME
                    ),
                ),
            ],
        ),
    ]
