# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-21 15:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0122_assessment_id_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenttag",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tags",
                to="contentcuration.Channel",
            ),
        ),
    ]
