# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-27 20:39
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0123_auto_20210407_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feature_flags',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
