# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-04 16:45
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0123_auto_20200921_1536"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentnode",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="created"
            ),
        ),
    ]
