# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-27 20:39
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0124_user_feature_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="feature_flags",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, null=True
            ),
        ),
    ]
