# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-02 22:41
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0125_auto_20201202_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disk_space_used',
            field=models.FloatField(default=0, help_text='How many bytes a user has uploaded'),
        ),
    ]
