# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-07 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0124_auto_20201204_1645'),
        ('contentcuration', '0125_auto_20201202_2240'),
    ]

    operations = [
    ]
