# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-07 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0126_merge_20201207_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnode',
            name='complete',
            field=models.NullBooleanField(),
        ),
    ]
