# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-09 05:33
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0126_merge_20201207_2127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentitem',
            unique_together=set([('contentnode', 'assessment_id')]),
        ),
    ]
