# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-07 18:21
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
import mptt.fields
from django.db import migrations
from django.db import models

import contentcuration.models
from contentcuration.models import ContentMetadata


def create_some_metadata(apps, schema_editor):
    subjects = ContentMetadata.objects.create(metadata_name="Subjects")
    maths = ContentMetadata.objects.create(metadata_name="Maths", parent=subjects)
    arithmethic = ContentMetadata.objects.create(
        metadata_name="Arithmetic", parent=maths
    )
    algebra = ContentMetadata.objects.create(metadata_name="Algebra", parent=maths)
    science = ContentMetadata.objects.create(metadata_name="Science", parent=subjects)
    physics = ContentMetadata.objects.create(metadata_name="Physics", parent=science)
    forces = ContentMetadata.objects.create(
        metadata_name="Forces and Motion", parent=physics
    )


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0126_merge_20201207_2127"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentMetadata",
            fields=[
                (
                    "id",
                    contentcuration.models.UUIDField(
                        default=uuid.uuid4,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metadata_name", models.CharField(max_length=150)),
                ("lft", models.PositiveIntegerField(db_index=True, editable=False)),
                ("rght", models.PositiveIntegerField(db_index=True, editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(db_index=True, editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="contentcuration.ContentMetadata",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="contentnode",
            name="metadata",
            field=models.ManyToManyField(
                blank=True,
                related_name="metadata_content",
                to="contentcuration.ContentMetadata",
            ),
        ),
        migrations.RunPython(create_some_metadata),
    ]
