# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-12 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0127_auto_20210107_1707'),
        ('contentcuration', '0114_assessment_item_unique_keypair'),
    ]

    operations = [
    ]
