# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-12 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0128_merge_20210112_1828'),
        ('contentcuration', '0127_invitation_status_fields'),
    ]

    operations = [
    ]
