# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-13 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0129_auto_20210113_1723'),
        ('contentcuration', '0129_merge_20210112_2327'),
    ]

    operations = [
    ]
