# Generated by Django 2.2.17 on 2021-05-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0129_auto_20210519_1759'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='contentcura_email_d4d492_idx',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(is_active=True), fields=('email',), name='contentcura_email_d4d492_idx'),
        ),
    ]
