# Generated by Django 3.2.4 on 2021-07-07 23:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0130_auto_20210706_2005"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChannelResourceSize",
        ),
    ]
