# Generated by Django 3.2.4 on 2021-07-08 00:11
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0131_auto_20210707_2326"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Exercise",
        ),
    ]
