# Generated by Django 3.2.4 on 2021-09-16 17:30
import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0132_auto_20210708_0011"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentnode",
            name="accessibilityArray",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=132),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="accessibilityStr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="categoryArray",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=132),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="categoryStr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="gradeLevelArray",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=132),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="gradeLevelStr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="labelsJson",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="learningActivityArray",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=132),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="learningActivityStr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="resourceTypeArray",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=132),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="resourceTypeStr",
            field=models.TextField(blank=True, null=True),
        ),
    ]
