# Generated by Django 3.2.4 on 2021-09-27 18:20
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0132_auto_20210708_0011"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentnode",
            name="accessibility_labels",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="category_labels",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="grade_level_labels",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="learning_activity_labels",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="resource_type_labels",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="contentnode",
            index=models.Index(
                fields=["grade_level_labels"], name="grade_level_label_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentnode",
            index=models.Index(
                fields=["resource_type_labels"], name="resource_type_label_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentnode",
            index=models.Index(
                fields=["learning_activity_labels"], name="learning_activity_label_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentnode",
            index=models.Index(fields=["category_labels"], name="category_label_idx"),
        ),
    ]
