# Generated by Django 3.2.5 on 2022-02-02 22:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0132_auto_20210708_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentkind',
            name='kind',
            field=models.CharField(choices=[('topic', 'Topic'), ('video', 'Video'), ('audio', 'Audio'), ('exercise', 'Exercise'), ('document', 'Document'), ('html5', 'HTML5 App'), ('slideshow', 'Slideshow'), ('h5p', 'H5P'), ('zim', 'Zim'), ('quiz', 'Quiz')], max_length=200, primary_key=True, serialize=False),
        ),
    ]
