# Generated by Django 3.2.4 on 2021-09-17 17:52
import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0133_auto_20210916_1730"),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name="contentnode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["gradeLevelStr"], name="gradeLevelStr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentnode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["resourceTypeStr"], name="resourceTypeStr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentnode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["learningActivityStr"], name="learningActivityStr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentnode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["accessibilityStr"], name="accessibilityStr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentnode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["categoryStr"], name="categoryStr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentnode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["gradeLevelArray"], name="gradeLevelArray_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentnode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["resourceTypeArray"], name="resourceTypeArray_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentnode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["learningActivityArray"], name="learningActivityArray_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentnode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["categoryArray"], name="categoryArray_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentnode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["labelsJson"], name="labelsJson_idx"
            ),
        ),
    ]
