# Generated by Django 3.2.5 on 2022-04-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0136_contentnode_suggested_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='os_validators',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contentnode',
            name='screen_reader',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
