# Generated by Django 3.2.13 on 2022-07-26 18:18
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0139_django_celery_results"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
