# Generated by Django 3.2.13 on 2022-08-10 19:20
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.contrib.postgres.operations import AddIndexConcurrently
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('contentcuration', '0140_delete_task'),
    ]

    operations = [
        # Installs the pg_trgm module that comes pre-bundled with PostgreSQL 9.6.
        TrigramExtension(),

        migrations.AddField(
            model_name='contentnode',
            name='title_description_search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        AddIndexConcurrently(
            model_name='contentnode',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_description_search_vector'], name='node_search_vector_gin_idx'),
        ),
        AddIndexConcurrently(
            model_name='contenttag',
            index=django.contrib.postgres.indexes.GistIndex(fields=['tag_name'], name='contenttag_tag_name_gist_idx', opclasses=['gist_trgm_ops']),
        ),
    ]
