# Generated by Django 3.2.14 on 2022-10-06 11:18
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0140_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
