# Generated by Django 3.2.18 on 2023-04-26 18:55
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0141_add_task_signature"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="file",
            name="file_media_duration_int",
        ),
    ]
