# Generated by Django 3.2.14 on 2023-05-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0142_add_task_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedCaptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('generated_captions', models.JSONField()),
                ('language', models.CharField(max_length=10)),
            ],
        ),
    ]
