# Generated by Django 3.2.19 on 2023-09-13 17:34
from django.db import migrations

class Migration(migrations.Migration):

    def __init__(self, name, app_label):
        super(Migration, self).__init__(name, 'django_celery_results')

    dependencies = [
        ('contentcuration', '0145_auto_20230913_1733'),
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskresult',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='taskresult',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='taskresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskresult',
            name='signature',
        ),
        migrations.RemoveIndex(
            model_name='taskresult',
            name='task_result_signature_idx',
        ),
    ]
