# Generated by Django 3.2.19 on 2023-09-14 10:42
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ("django_celery_results", "0145_custom_task_metadata"),
    ]

    def __init__(self, name, app_label):
        super(Migration, self).__init__(name, "django_celery_results")

    dependencies = [
        ("contentcuration", "0145_custom_task_metadata"),
        ("contentcuration", "0141_add_task_signature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskresult",
            name="channel_id",
        ),
        migrations.RemoveField(
            model_name="taskresult",
            name="progress",
        ),
        migrations.RemoveField(
            model_name="taskresult",
            name="user",
        ),
        migrations.RemoveField(
            model_name="taskresult",
            name="signature",
        ),
        migrations.RemoveIndex(
            model_name="taskresult",
            name="task_result_signature_idx",
        ),
    ]
