# Generated by Django 3.2.19 on 2023-11-01 19:54
import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models

import contentcuration.models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0146_drop_taskresult_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptionFile',
            fields=[
                ('id', contentcuration.models.UUIDField(default=uuid.uuid4, max_length=32, primary_key=True, serialize=False)),
                ('file_id', contentcuration.models.UUIDField(default=uuid.uuid4, max_length=32)),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caption_file', to='contentcuration.language')),
                ('output_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contentcuration.file')),
            ],
            options={
                'unique_together': {('file_id', 'language')},
            },
        ),
        migrations.CreateModel(
            name='CaptionCue',
            fields=[
                ('id', contentcuration.models.UUIDField(default=uuid.uuid4, max_length=32, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('starttime', models.FloatField()),
                ('endtime', models.FloatField()),
                ('caption_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caption_cue', to='contentcuration.captionfile')),
            ],
        ),
    ]
