# Generated by Django 3.2.19 on 2023-11-01 12:00
from django.db import migrations
from django.db import models
from pgvector.django import VectorExtension
from pgvector.django import VectorField

import contentcuration.models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0146_drop_taskresult_fields'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Embeddings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', contentcuration.models.UUIDField(max_length=32)),
                ('embedding', VectorField()),
            ],
        ),
        migrations.AddIndex(
            model_name='embeddings',
            index=models.Index(fields=['content_id'], name='contentcura_content_e09ec2_idx'),
        ),
    ]
