# Generated by Django 3.2.19 on 2023-11-08 09:55
import uuid

import django.db.models.deletion
import pgvector.django
from django.conf import settings
from django.db import migrations
from django.db import models

import contentcuration.models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0147_alter_formatpreset_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingsContentNode',
            fields=[
                ('cid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('contentnode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_cid', to='contentcuration.contentnode')),
            ],
        ),
        migrations.CreateModel(
            name='Embeddings',
            fields=[
                ('embedding_id', contentcuration.models.UUIDField(default=uuid.uuid4, max_length=32, primary_key=True, serialize=False)),
                ('model', models.CharField(db_index=True, max_length=64)),
                ('embedding', pgvector.django.VectorField()),
                ('embedded_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='contentcuration.embeddingscontentnode')),
            ],
        ),
    ]
