# Generated by Django 3.2.24 on 2025-01-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0150_bloompub_format_and_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentitem',
            name='type',
            field=models.CharField(choices=[('input_question', 'Input Question'), ('multiple_selection', 'Multiple Selection'), ('single_selection', 'Single Selection'), ('free_response', 'Free Response'), ('perseus_question', 'Perseus Question')], default='multiple_selection', max_length=50),
        ),
    ]
