# Generated by Django 3.2.24 on 2025-04-17 16:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0151_auto_20250417_1516"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentitem",
            name="type",
            field=models.CharField(
                choices=[
                    ("input_question", "Input Question"),
                    ("multiple_selection", "Multiple Selection"),
                    ("single_selection", "Single Selection"),
                    ("free_response", "Free Response"),
                    ("perseus_question", "Perseus Question"),
                ],
                default="multiple_selection",
                max_length=50,
            ),
        ),
    ]
