# Generated by Django 3.2.24 on 2025-02-23 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0151_alter_assessmentitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='support_token',
            field=models.OneToOneField(blank=True, help_text='Token for support access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_channels', to='contentcuration.secrettoken', verbose_name='support token'),
        ),
    ]
