# Generated by Django 3.2.24 on 2025-05-16 07:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0152_alter_assessmentitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationsevent',
            name='time_hidden',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
