# Generated by Django 3.2.24 on 2025-07-03 17:06
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0153_alter_recommendationsevent_time_hidden"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="alpha-2 country code",
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CommunityLibrarySubmission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("channel_version", models.PositiveIntegerField()),
                ("categories", models.JSONField(blank=True, default=list, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("LIVE", "Live"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_library_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_library_submissions",
                        to="contentcuration.channel",
                    ),
                ),
                (
                    "countries",
                    models.ManyToManyField(
                        related_name="community_library_submissions",
                        to="contentcuration.Country",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="communitylibrarysubmission",
            constraint=models.UniqueConstraint(
                fields=("channel", "channel_version"),
                name="unique_channel_with_channel_version",
            ),
        ),
    ]
