# Generated by Django 3.2.24 on 2025-07-08 20:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0154_community_library_submission"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="communitylibrarysubmission",
            index=models.Index(
                fields=["-date_created"], name="submission_date_created_idx"
            ),
        ),
    ]
