# Generated by Django 3.2.24 on 2025-07-15 19:12
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contentcuration",
            "0155_communitylibrarysubmission_submission_date_created_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="communitylibrarysubmission",
            name="date_resolved",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="communitylibrarysubmission",
            name="feedback_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="communitylibrarysubmission",
            name="internal_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="communitylibrarysubmission",
            name="resolution_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INVALID_LICENSING", "Invalid Licensing"),
                    ("TECHNICAL_QUALITY_ASSURANCE", "Technical Quality Assurance"),
                    ("INVALID_METADATA", "Invalid Metadata"),
                    ("PORTABILITY_ISSUES", "Portability Issues"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="communitylibrarysubmission",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_community_library_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="communitylibrarysubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("SUPERSEDED", "Superseded"),
                    ("LIVE", "Live"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
