# Generated by Django 3.2.24 on 2025-10-15 03:33
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0154_alter_assessmentitem_type"),
        ("contentcuration", "0156_communitylibrarysubmission_admin_fields"),
    ]

    operations = []
