# Generated by Django 3.2.24 on 2025-07-15 20:11
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0156_communitylibrarysubmission_admin_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitylibrarysubmission",
            name="resolution_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INVALID_LICENSING", "Invalid Licensing"),
                    ("TECHNICAL_QUALITY_ASSURANCE", "Technical Quality Assurance"),
                    ("INVALID_METADATA", "Invalid Metadata"),
                    ("PORTABILITY_ISSUES", "Portability Issues"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
