# Generated by Django 3.2.24 on 2025-11-22 23:51
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0157_merge_20251015_0333"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="communitylibrarysubmission",
            name="submission_date_created_idx",
        ),
        migrations.RemoveField(
            model_name="communitylibrarysubmission",
            name="date_resolved",
        ),
        migrations.AddField(
            model_name="communitylibrarysubmission",
            name="date_updated",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="communitylibrarysubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("SUPERSEDED", "Superseded"),
                    ("LIVE", "Live"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="communitylibrarysubmission",
            index=models.Index(
                fields=["-date_updated"], name="submission_date_updated_idx"
            ),
        ),
    ]
