# Generated by Django 3.2.24 on 2025-11-05 22:17
import uuid

from django.db import migrations
from django.db import models

import contentcuration.models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0157_merge_20251015_0333"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditedSpecialPermissionsLicense",
            fields=[
                (
                    "id",
                    contentcuration.models.UUIDField(
                        default=uuid.uuid4,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(db_index=True, unique=True)),
                ("distributable", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddIndex(
            model_name="auditedspecialpermissionslicense",
            index=models.Index(
                fields=["description"], name="audited_special_perms_desc_idx"
            ),
        ),
    ]
