# Generated by Django 3.2.24 on 2025-10-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0157_merge_20251015_0333'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='communitylibrarysubmission',
            name='unique_channel_with_channel_version',
        ),
    ]
