# Generated by Django 3.2.24 on 2025-11-30 23:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0158_add_audited_special_permissions_license"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="communitylibrarysubmission",
            name="submission_date_created_idx",
        ),
        migrations.RemoveField(
            model_name="communitylibrarysubmission",
            name="date_resolved",
        ),
        migrations.AddField(
            model_name="communitylibrarysubmission",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="communitylibrarysubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("SUPERSEDED", "Superseded"),
                    ("LIVE", "Live"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
