# Generated by Django 3.2.24 on 2025-11-30 23:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0157_merge_20251015_0333"),
    ]

    operations = [
        migrations.RenameField(
            model_name="communitylibrarysubmission",
            old_name="date_resolved",
            new_name="date_updated",
        ),
        migrations.AlterField(
            model_name="communitylibrarysubmission",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
