# Generated by Django 3.2.24 on 2025-12-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0159_update_community_library_submission_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitylibrarysubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded'), ('LIVE', 'Live')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
