# Generated by Django 3.2.24 on 2026-01-19 17:37
import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0160_add_channel_version_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelversion",
            name="included_categories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("d&WXdXWF.qs0Xlaxq.0t5msbL5", "Algebra"),
                        ("d&WXdXWF.K80UMYnW.ViBlbQR&", "Anthropology"),
                        ("d&WXdXWF.qs0Xlaxq.nG96nHDc", "Arithmetic"),
                        ("d&WXdXWF.5QAjgfv7", "Arts"),
                        ("d&WXdXWF.i1IdaNwr.mjSF4QlF", "Astronomy"),
                        ("d&WXdXWF.i1IdaNwr.uErN4PdS", "Biology"),
                        ("d&WXdXWF.qs0Xlaxq.8rJ57ht6", "Calculus"),
                        ("d&WXdXWF.i1IdaNwr.#r5ocgid", "Chemistry"),
                        ("d&WXdXWF.K80UMYnW.F863vKiF", "Civic Education"),
                        ("d&WXdXWF.e#RTW9E#", "Computer Science"),
                        ("PbGoe2MV.J7CU1IxN", "Current Events"),
                        ("PbGoe2MV", "Daily Life"),
                        ("d&WXdXWF.5QAjgfv7.BUMJJBnS", "Dance"),
                        ("BCG3&slG.wZ3EAedB", "Digital Literacy"),
                        ("PbGoe2MV.EHcbjuKq", "Diversity"),
                        ("d&WXdXWF.5QAjgfv7.XsWznP4o", "Drama"),
                        ("d&WXdXWF.i1IdaNwr.zbDzxDE7", "Earth Science"),
                        ("PbGoe2MV.kyxTNsRS", "Entrepreneurship"),
                        ("PbGoe2MV.tS7WKnZ7", "Environment"),
                        ("PbGoe2MV.HGIc9sZq", "Financial Literacy"),
                        ("ziJ6PCuU", "For Teachers"),
                        ("BCG3&slG", "Foundations"),
                        (
                            "BCG3&slG.0&d0qTqS",
                            "Foundations Logic And Critical Thinking",
                        ),
                        ("d&WXdXWF.qs0Xlaxq.lb7ELcK5", "Geometry"),
                        ("ziJ6PCuU.RLfhp37t", "Guides"),
                        ("d&WXdXWF.zWtcJ&F2", "History"),
                        ("l7DsPDlm.ISEXeZt&.pRvOzJTE", "Industry And Sector Specific"),
                        ("d&WXdXWF.JDUfJNXc", "Language Learning"),
                        ("BCG3&slG.fP2j70bj", "Learning Skills"),
                        ("ziJ6PCuU.lOBPr5ix", "Lesson Plans"),
                        ("BCG3&slG.HLo9TbNq", "Literacy"),
                        ("d&WXdXWF.kHKJ&PbV.DJLBbaEk", "Literature"),
                        ("d&WXdXWF.kHKJ&PbV.YMBXStib", "Logic And Critical Thinking"),
                        ("d&WXdXWF.qs0Xlaxq", "Mathematics"),
                        ("d&WXdXWF.e#RTW9E#.8ZoaPsVW", "Mechanical Engineering"),
                        ("PbGoe2MV.UOTL#KIV", "Media Literacy"),
                        ("PbGoe2MV.d8&gCo2N", "Mental Health"),
                        ("d&WXdXWF.5QAjgfv7.u0aKjT4i", "Music"),
                        ("BCG3&slG.Tsyej9ta", "Numeracy"),
                        ("d&WXdXWF.i1IdaNwr.r#wbt#jF", "Physics"),
                        ("d&WXdXWF.K80UMYnW.K72&pITr", "Political Science"),
                        ("l7DsPDlm.#N2VymZo", "Professional Skills"),
                        ("d&WXdXWF.e#RTW9E#.CfnlTDZ#", "Programming"),
                        ("PbGoe2MV.kivAZaeX", "Public Health"),
                        ("d&WXdXWF.kHKJ&PbV", "Reading And Writing"),
                        ("d&WXdXWF.kHKJ&PbV.r7RxB#9t", "Reading Comprehension"),
                        ("d&WXdXWF", "School"),
                        ("d&WXdXWF.i1IdaNwr", "Sciences"),
                        ("l7DsPDlm.ISEXeZt&.&1WpYE&n", "Skills Training"),
                        ("d&WXdXWF.K80UMYnW", "Social Sciences"),
                        ("d&WXdXWF.K80UMYnW.75WBu1ZS", "Sociology"),
                        ("d&WXdXWF.qs0Xlaxq.jNm15RLB", "Statistics"),
                        ("l7DsPDlm.ISEXeZt&", "Technical And Vocational Training"),
                        ("l7DsPDlm.ISEXeZt&.1JfIbP&N", "Tools And Software Training"),
                        ("d&WXdXWF.5QAjgfv7.4LskOFXj", "Visual Art"),
                        ("d&WXdXWF.e#RTW9E#.P7s8FxQ8", "Web Design"),
                        ("l7DsPDlm", "Work"),
                        ("d&WXdXWF.kHKJ&PbV.KFJOCr&6", "Writing"),
                    ],
                    max_length=100,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="channelversion",
            name="included_licenses",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (1, "CC BY"),
                        (2, "CC BY-SA"),
                        (3, "CC BY-ND"),
                        (4, "CC BY-NC"),
                        (5, "CC BY-NC-SA"),
                        (6, "CC BY-NC-ND"),
                        (7, "All Rights Reserved"),
                        (8, "Public Domain"),
                        (9, "Special Permissions"),
                    ]
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="channelversion",
            name="non_distributable_licenses_included",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (1, "CC BY"),
                        (2, "CC BY-SA"),
                        (3, "CC BY-ND"),
                        (4, "CC BY-NC"),
                        (5, "CC BY-NC-SA"),
                        (6, "CC BY-NC-ND"),
                        (7, "All Rights Reserved"),
                        (8, "Public Domain"),
                        (9, "Special Permissions"),
                    ]
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
