# Generated by Django 3.2.24 on 2025-12-17 00:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0161_update_channelversion_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_read_notification_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="newest_notification_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
