# Generated by Django 3.2.24 on 2026-03-20 18:09
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0155_fix_language_foreign_key_length"),
        ("contentcuration", "0162_add_notification_timestamps_20251217_0055"),
    ]

    operations = []
