# Generated by Django 3.2.24 on 2026-03-24 18:10
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0163_merge_20260320_1809"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelversion",
            name="channel_description",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="channelversion",
            name="channel_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contentcuration.language",
            ),
        ),
        migrations.AddField(
            model_name="channelversion",
            name="channel_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="channelversion",
            name="channel_tagline",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="channelversion",
            name="channel_thumbnail_encoding",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
