# Generated by Django 3.2.24 on 2026-03-31 14:45
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0164_add_channel_info_snapshot_to_channelversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelversion",
            name="size",
            field=models.FloatField(default=0),
        ),
    ]
