# Generated by Django 3.2.24 on 2026-04-02 03:53
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0165_alter_channelversion_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "stripe_subscription_status",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "subscription_disk_space",
                    models.BigIntegerField(
                        default=0, help_text="Additional bytes granted by subscription"
                    ),
                ),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contentcuration_usersubscription",
            },
        ),
    ]
