# Generated by Django 3.2.24 on 2026-06-25 01:47
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import contentcuration.models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0166_add_usersubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    contentcuration.models.UUIDField(
                        default=uuid.uuid4,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("thumbnail", models.TextField(blank=True, null=True)),
                ("thumbnail_encoding", models.JSONField(default=dict)),
                (
                    "public",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether organization is publicly visible",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Soft delete flag"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="channel",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that this channel belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="channel_organization",
                to="contentcuration.organization",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationRole",
            fields=[
                (
                    "id",
                    contentcuration.models.UUIDField(
                        default=uuid.uuid4,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        help_text="The user's role within the organization.",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the user's role within the organization",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending Invitation"),
                            ("suspended", "Suspended"),
                            ("declined", "Declined Invitation"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Membership status",
                        max_length=20,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date user joined the organization"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization the user belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="contentcuration.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User in the organization",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Role",
                "verbose_name_plural": "Organization Roles",
                "ordering": ["-joined_at"],
                "unique_together": {("user", "organization")},
            },
        ),
    ]
