# Generated by Django 3.2.24 on 2026-06-23 05:56
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations
from django.db import models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0166_add_usersubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_size_bigint",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["checksum", "file_size_bigint"],
                name="file_checksum_fsizebig_idx",
                condition=Q(file_size_bigint__isnull=False),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="mirror_file_size_to_file_size_bigint",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="IF NEW.file_size IS DISTINCT FROM OLD.file_size THEN NEW.file_size_bigint = NEW.file_size; END IF; RETURN NEW;",
                    hash="051e321c4cdf91ea81f96b9f9a29e3b5015def67",
                    operation="INSERT OR UPDATE",
                    pgid="pgtrigger_mirror_file_size_to_file_size_bigint_54326",
                    table="contentcuration_file",
                    when="BEFORE",
                ),
            ),
        ),
    ]
