# Generated by Django 3.2.25 on 2026-07-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0167_file_size_bigint_expand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentitem',
            name='type',
            field=models.CharField(choices=[('input_question', 'Input Question'), ('multiple_selection', 'Multiple Selection'), ('single_selection', 'Single Selection'), ('free_response', 'Free Response'), ('perseus_question', 'Perseus Question'), ('QTI', 'QTI'), ('true_false', 'True/False')], default='multiple_selection', max_length=50),
        ),
    ]
