# Generated by Django 3.2.24 on 2026-06-27 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0167_add_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contentcuration.organization'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('channel__isnull', False), ('organization__isnull', True)), models.Q(('channel__isnull', True), ('organization__isnull', False)), _connector='OR'), name='channel_organization_exclusivity'),
        ),
    ]
