# Generated by Django 3.2.24 on 2026-07-02 04:15
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0168_alter_assessmentitem_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contentcuration.organization",
            ),
        ),
    ]
