# Generated by Django 3.2.24 on 2026-07-17 01:36
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0167_file_size_bigint_expand"),
        ("contentcuration", "0169_invitation_organization"),
    ]

    operations = []
