STATUS_PENDING = "PENDING"
STATUS_APPROVED = "APPROVED"
STATUS_REJECTED = "REJECTED"
STATUS_LIVE = "LIVE"

COMMUNITY_LIBRARY_SUBMISSION_STATUS_CHOICES = (
    (STATUS_PENDING, "Pending"),
    (STATUS_APPROVED, "Approved"),
    (STATUS_REJECTED, "Rejected"),
    (STATUS_LIVE, "Live"),
)
