STATUS_PENDING = "PENDING"
STATUS_APPROVED = "APPROVED"
STATUS_REJECTED = "REJECTED"
STATUS_SUPERSEDED = "SUPERSEDED"
STATUS_LIVE = "LIVE"

status_choices = (
    (STATUS_PENDING, "Pending"),
    (STATUS_APPROVED, "Approved"),
    (STATUS_REJECTED, "Rejected"),
    (STATUS_SUPERSEDED, "Superseded"),
    (STATUS_LIVE, "Live"),
)

REASON_INVALID_LICENSING = "INVALID_LICENSING"
REASON_TECHNICAL_QUALITY_ASSURANCE = "TECHNICAL_QUALITY_ASSURANCE"
REASON_INVALID_METADATA = "INVALID_METADATA"
REASON_PORTABILITY_ISSUES = "PORTABILITY_ISSUES"
REASON_OTHER = "OTHER"

resolution_reason_choices = (
    (REASON_INVALID_LICENSING, "Invalid Licensing"),
    (REASON_TECHNICAL_QUALITY_ASSURANCE, "Technical Quality Assurance"),
    (REASON_INVALID_METADATA, "Invalid Metadata"),
    (REASON_PORTABILITY_ISSUES, "Portability Issues"),
    (REASON_OTHER, "Other"),
)
