ORGANIZATION_ADMIN = "admin"
ORGANIZATION_EDITOR = "editor"
ORGANIZATION_VIEWER = "viewer"

organization_role_choices = (
    (ORGANIZATION_ADMIN, "Admin"),
    (ORGANIZATION_EDITOR, "Editor"),
    (ORGANIZATION_VIEWER, "Viewer"),
)

# Viewing is ORGANIZATION_VIEWER alone; admins/editors are already admitted via the edit check.
ORGANIZATION_CHANNEL_EDIT_ROLES = (ORGANIZATION_ADMIN, ORGANIZATION_EDITOR)

ORGANIZATION_ROLE_STATUS_ACTIVE = "active"
ORGANIZATION_ROLE_STATUS_INACTIVE = "inactive"
ORGANIZATION_ROLE_STATUS_PENDING = "pending"
ORGANIZATION_ROLE_STATUS_SUSPENDED = "suspended"
ORGANIZATION_ROLE_STATUS_DECLINED = "declined"

organization_role_status_choices = (
    (ORGANIZATION_ROLE_STATUS_ACTIVE, "Active"),
    (ORGANIZATION_ROLE_STATUS_INACTIVE, "Inactive"),
    (ORGANIZATION_ROLE_STATUS_PENDING, "Pending Invitation"),
    (ORGANIZATION_ROLE_STATUS_SUSPENDED, "Suspended"),
    (ORGANIZATION_ROLE_STATUS_DECLINED, "Declined Invitation"),
)
