FROM ubuntu:bionic

# Set the timezone
RUN ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime

# Studio source directory ######################################################
RUN mkdir /src
WORKDIR /src
################################################################################


# System packages ##############################################################
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update --fix-missing && \
    apt-get -y install \
        curl fish man \
        python python-dev python-pip \
        gcc libpq-dev ffmpeg imagemagick unzip \
        ghostscript python-tk make git gettext libjpeg-dev \
        wkhtmltopdf fonts-freefont-ttf xfonts-75dpi poppler-utils

# Download and install libpng12, a dependency of wkhtmltox
RUN curl -L -o libpng12.deb http://security.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1.1_amd64.deb && \
    dpkg -i libpng12.deb && \
    rm libpng12.deb

# Download and install wkhtmltox
RUN curl -L -o wkhtmltox.deb https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb && \
    dpkg -i wkhtmltox.deb && \
    rm wkhtmltox.deb

# Download then install node
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - &&\
    apt-get install -y nodejs
################################################################################


# Node packages ################################################################
RUN npm install -g yarn && npm cache clean --force
COPY ./package.json ./yarn.lock   /src/
RUN  yarn install --network-timeout 1000000 --pure-lockfile && yarn cache clean
################################################################################


# Python packages ##############################################################
COPY Pipfile Pipfile.lock   /src/
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -U pipenv
# install packages from Pipfile.lock into system
RUN pipenv install --clear --dev --system --ignore-pipfile
################################################################################


# Final cleanup ################################################################
RUN apt-get -y autoremove
################################################################################

CMD ["yarn", "run", "devserver"]
