# location {} settings for /content caching
# used by files in this directory, via `include` directive

# ignore 'expires' and 'cache-control' headers from upstream so this value is authoritative
proxy_hide_header Cache-Control;
proxy_hide_header Expires;

# content is md5-addressed, so cache aggressively for successful responses
add_header Cache-Control "public, max-age=31536000, immutable, no-transform";
