# location {} settings for /content caching
# used by files in this directory, via `include` directive

# ignore cache-control from upstream so this value is authoritative
proxy_hide_header Cache-Control;

# content is md5-addressed, so cache aggressively for successful responses
add_header Cache-Control "public, max-age=31536000, immutable, no-transform";
