# DO NOT RENAME: this file is named after the primary bucket it proxies to

location @hotfixes {
    include /etc/nginx/includes/content/_proxy.conf;

    # this is the magic that allows us to intercept errors and try the next location
    proxy_intercept_errors on;
    recursive_error_pages on;
    error_page 404 = @production;

    proxy_pass https://develop-studio-content.storage.googleapis.com;
}

location @production {
    include /etc/nginx/includes/content/_proxy.conf;

    proxy_pass https://studio-content.storage.googleapis.com;
}

location @hotfixes_storage {
    include /etc/nginx/includes/content/_proxy.conf;
    include /etc/nginx/includes/content/_cache.conf;

    # this is the magic that allows us to intercept errors and try the next location
    proxy_intercept_errors on;
    recursive_error_pages on;
    error_page 404 = @production_storage;

    proxy_pass https://develop-studio-content.storage.googleapis.com;
}

location @production_storage {
    include /etc/nginx/includes/content/_proxy.conf;
    include /etc/nginx/includes/content/_cache.conf;

    proxy_pass https://studio-content.storage.googleapis.com;
}

location @nowhere {
    return 404;
}

# Note on try_files
# -----------------
# try_files will only use one named route, and it uses the last one. Although, we can't just pass
# one named route, because it fails.

location ^~ /content/storage/ {
    # ensure that the /content/ prefix is stripped from the request
    rewrite ^/content/(.*)$ /$1 break;

    # check staging bucket first, then fall back to production
    try_files @nowhere @hotfixes_storage;
}

location /content/ {
    # ensure that the /content/ prefix is stripped from the request
    rewrite ^/content/(.*)$ /$1 break;

    # check the emulator bucket first, then cloud development bucket, then fall back to production
    try_files @nowhere @hotfixes;
}
