# Generated by Django 3.2.14 on 2023-03-14 01:07
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("kolibri_public", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MPTTTreeIDManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
