# Generated by Django 3.2.24 on 2025-07-22 10:38
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0156_communitylibrarysubmission_admin_fields"),
        ("kolibri_public", "0006_auto_20250417_1516"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelmetadata",
            name="categories",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="channelmetadata",
            name="countries",
            field=models.ManyToManyField(
                related_name="public_channels", to="contentcuration.Country"
            ),
        ),
    ]
