# Generated by Django 3.2.24 on 2025-08-08 17:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("kolibri_public", "0007_new_channel_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelmetadata",
            name="categories_bitmask_0",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
