# Generated by Django 3.2.25 on 2026-07-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibri_public', '0008_channelmetadata_categories_bitmask_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='included_presets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
