# Generated by Django 3.2.24 on 2026-09-24 21:28
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("kolibri_public", "0010_localfile_file_size_bigint"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentnode",
            name="modality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COURSE", "Course"),
                    ("CUSTOM_NAVIGATION", "Custom Navigation"),
                    ("LESSON", "Lesson"),
                    ("QUIZ", "Quiz"),
                    ("SURVEY", "Survey"),
                    ("UNIT", "Unit"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        AddIndexConcurrently(
            model_name="contentnode",
            index=models.Index(
                fields=["modality"], name="kolibri_pub_modalit_1ae095_idx"
            ),
        ),
    ]
