// Constant values for FormatPresets sorted by id
const FormatPresetsMap = new Map([
  ["audio", {
    associated_mimetypes: [".mp3"],
    subtitle: false,
    allowed_formats: ["mp3"],
    readable_name: "Audio",
    supplementary: false,
    thumbnail: false,
    multi_language: false,
    id: "audio",
    kind_id: "audio",
    order: 1,
    display: true,
  }],
  ["audio_thumbnail", {
    associated_mimetypes: ["image/png", "image/jpeg"],
    subtitle: false,
    allowed_formats: ["png", "jpg", "jpeg"],
    readable_name: "Thumbnail",
    supplementary: true,
    thumbnail: true,
    multi_language: false,
    id: "audio_thumbnail",
    kind_id: "audio",
    order: 2,
    display: true,
  }],
  ["channel_thumbnail", {
    associated_mimetypes: ["image/png", "image/jpeg"],
    subtitle: false,
    allowed_formats: ["png", "jpg", "jpeg"],
    readable_name: "Channel Thumbnail",
    supplementary: true,
    thumbnail: true,
    multi_language: false,
    id: "channel_thumbnail",
    kind_id: null,
    order: 0,
    display: true,
  }],
  ["document", {
    associated_mimetypes: ["application/pdf"],
    subtitle: false,
    allowed_formats: ["pdf"],
    readable_name: "Document",
    supplementary: false,
    thumbnail: false,
    multi_language: false,
    id: "document",
    kind_id: "document",
    order: 2,
    display: true,
  }],
  ["document_thumbnail", {
    associated_mimetypes: ["image/png", "image/jpeg"],
    subtitle: false,
    allowed_formats: ["png", "jpg", "jpeg"],
    readable_name: "Thumbnail",
    supplementary: true,
    thumbnail: true,
    multi_language: false,
    id: "document_thumbnail",
    kind_id: "document",
    order: 3,
    display: true,
  }],
  ["epub", {
    associated_mimetypes: ["application/epub+zip"],
    subtitle: false,
    allowed_formats: ["epub"],
    readable_name: "ePub Document",
    supplementary: false,
    thumbnail: false,
    multi_language: false,
    id: "epub",
    kind_id: "document",
    order: 1,
    display: true,
  }],
  ["exercise", {
    associated_mimetypes: ["application/perseus+zip"],
    subtitle: false,
    allowed_formats: ["perseus"],
    readable_name: "Exercise",
    supplementary: false,
    thumbnail: false,
    multi_language: false,
    id: "exercise",
    kind_id: "exercise",
    order: 1,
    display: false,
  }],
  ["exercise_graphie", {
    associated_mimetypes: ["application/json", ".graphie", "image/svg"],
    subtitle: false,
    allowed_formats: ["svg", "json", "graphie"],
    readable_name: "Exercise Graphie",
    supplementary: true,
    thumbnail: false,
    multi_language: false,
    id: "exercise_graphie",
    kind_id: "exercise",
    order: 4,
    display: false,
  }],
  ["exercise_image", {
    associated_mimetypes: ["image/gif", "image/png", "image/svg", "image/jpeg"],
    subtitle: false,
    allowed_formats: ["png", "jpg", "jpeg", "gif", "svg"],
    readable_name: "Exercise Image",
    supplementary: true,
    thumbnail: false,
    multi_language: false,
    id: "exercise_image",
    kind_id: "exercise",
    order: 3,
    display: false,
  }],
  ["exercise_thumbnail", {
    associated_mimetypes: ["image/png", "image/jpeg"],
    subtitle: false,
    allowed_formats: ["png", "jpg", "jpeg"],
    readable_name: "Thumbnail",
    supplementary: true,
    thumbnail: true,
    multi_language: false,
    id: "exercise_thumbnail",
    kind_id: "exercise",
    order: 2,
    display: true,
  }],
  ["h5p", {
    associated_mimetypes: [".h5p"],
    subtitle: false,
    allowed_formats: ["h5p"],
    readable_name: "H5P",
    supplementary: false,
    thumbnail: false,
    multi_language: false,
    id: "h5p",
    kind_id: "h5p",
    order: 1,
    display: false,
  }],
  ["h5p_thumbnail", {
    associated_mimetypes: ["image/png", "image/jpeg"],
    subtitle: false,
    allowed_formats: ["png", "jpg", "jpeg"],
    readable_name: "H5P Thumbnail",
    supplementary: true,
    thumbnail: true,
    multi_language: false,
    id: "h5p_thumbnail",
    kind_id: "h5p",
    order: 2,
    display: true,
  }],
  ["high_res_video", {
    associated_mimetypes: ["video/mp4"],
    subtitle: false,
    allowed_formats: ["mp4"],
    readable_name: "High Resolution",
    supplementary: false,
    thumbnail: false,
    multi_language: false,
    id: "high_res_video",
    kind_id: "video",
    order: 1,
    display: true,
  }],
  ["html5_dependency", {
    associated_mimetypes: [".zip"],
    subtitle: false,
    allowed_formats: ["zip"],
    readable_name: "HTML5 Zip Dependency",
    supplementary: true,
    thumbnail: false,
    multi_language: false,
    id: "html5_dependency",
    kind_id: "html5",
    order: 3,
    display: false,
  }],
  ["html5_thumbnail", {
    associated_mimetypes: ["image/png", "image/jpeg"],
    subtitle: false,
    allowed_formats: ["png", "jpg", "jpeg"],
    readable_name: "HTML5 Thumbnail",
    supplementary: true,
    thumbnail: true,
    multi_language: false,
    id: "html5_thumbnail",
    kind_id: "html5",
    order: 2,
    display: true,
  }],
  ["html5_zip", {
    associated_mimetypes: [".zip"],
    subtitle: false,
    allowed_formats: ["zip"],
    readable_name: "HTML5 Zip",
    supplementary: false,
    thumbnail: false,
    multi_language: false,
    id: "html5_zip",
    kind_id: "html5",
    order: 1,
    display: true,
  }],
  ["low_res_video", {
    associated_mimetypes: ["video/mp4"],
    subtitle: false,
    allowed_formats: ["mp4"],
    readable_name: "Low Resolution",
    supplementary: false,
    thumbnail: false,
    multi_language: false,
    id: "low_res_video",
    kind_id: "video",
    order: 2,
    display: true,
  }],
  ["slideshow_image", {
    associated_mimetypes: ["image/png", "image/jpeg"],
    subtitle: false,
    allowed_formats: ["png", "jpg", "jpeg"],
    readable_name: "Slideshow Slide Image",
    supplementary: false,
    thumbnail: false,
    multi_language: false,
    id: "slideshow_image",
    kind_id: "slideshow",
    order: 3,
    display: false,
  }],
  ["slideshow_manifest", {
    associated_mimetypes: ["application/json"],
    subtitle: false,
    allowed_formats: ["json"],
    readable_name: "Slideshow Manifest",
    supplementary: false,
    thumbnail: false,
    multi_language: false,
    id: "slideshow_manifest",
    kind_id: "slideshow",
    order: 1,
    display: false,
  }],
  ["slideshow_thumbnail", {
    associated_mimetypes: ["image/png", "image/jpeg"],
    subtitle: false,
    allowed_formats: ["png", "jpg", "jpeg"],
    readable_name: "Slideshow Thumbnail",
    supplementary: true,
    thumbnail: true,
    multi_language: false,
    id: "slideshow_thumbnail",
    kind_id: "slideshow",
    order: 2,
    display: false,
  }],
  ["topic_thumbnail", {
    associated_mimetypes: ["image/png", "image/jpeg"],
    subtitle: false,
    allowed_formats: ["png", "jpg", "jpeg"],
    readable_name: "Thumbnail",
    supplementary: true,
    thumbnail: true,
    multi_language: false,
    id: "topic_thumbnail",
    kind_id: "topic",
    order: 1,
    display: true,
  }],
  ["video_dependency", {
    associated_mimetypes: ["video/mp4"],
    subtitle: false,
    allowed_formats: ["mp4"],
    readable_name: "Video Dependency",
    supplementary: true,
    thumbnail: false,
    multi_language: false,
    id: "video_dependency",
    kind_id: "video",
    order: 3,
    display: false,
  }],
  ["video_subtitle", {
    associated_mimetypes: [".vtt"],
    subtitle: true,
    allowed_formats: ["vtt"],
    readable_name: "Subtitle",
    supplementary: true,
    thumbnail: false,
    multi_language: true,
    id: "video_subtitle",
    kind_id: "video",
    order: 4,
    display: true,
  }],
  ["video_thumbnail", {
    associated_mimetypes: ["image/png", "image/jpeg"],
    subtitle: false,
    allowed_formats: ["png", "jpg", "jpeg"],
    readable_name: "Thumbnail",
    supplementary: true,
    thumbnail: true,
    multi_language: false,
    id: "video_thumbnail",
    kind_id: "video",
    order: 3,
    display: true,
  }],
]);

export default FormatPresetsMap

export const FormatPresetsList = Array.from(FormatPresetsMap.values());