// Constant values for Languages sorted by native_name
const LanguagesMap = new Map([
  [
    'ach',
    {
      readable_name: 'Acholi; Acooli; Akoli',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Acholi',
      lang_code: 'ach',
      id: 'ach',
    },
  ],
  [
    'om',
    {
      readable_name: 'Oromo',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Afaan Oromoo',
      lang_code: 'om',
      id: 'om',
    },
  ],
  [
    'aa',
    {
      readable_name: 'Afar',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Afaraf',
      lang_code: 'aa',
      id: 'aa',
    },
  ],
  [
    'af',
    {
      readable_name: 'Afrikaans',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Afrikaans',
      lang_code: 'af',
      id: 'af',
    },
  ],
  [
    'aka',
    {
      readable_name: 'Akan',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Akan',
      lang_code: 'aka',
      id: 'aka',
    },
  ],
  [
    'ak',
    {
      readable_name: 'Akan',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Akan',
      lang_code: 'ak',
      id: 'ak',
    },
  ],
  [
    'an',
    {
      readable_name: 'Aragonese',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Aragon\u00e9s',
      lang_code: 'an',
      id: 'an',
    },
  ],
  [
    'en-PT',
    {
      readable_name: 'English, Pirate',
      lang_subcode: 'PT',
      lang_direction: 'ltr',
      native_name: 'Argh! Pirates!',
      lang_code: 'en',
      id: 'en-PT',
    },
  ],
  [
    'ibo',
    {
      readable_name: 'Igbo',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'As\u1ee5s\u1ee5 Igbo',
      lang_code: 'ibo',
      id: 'ibo',
    },
  ],
  [
    'ig',
    {
      readable_name: 'Igbo',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'As\u1ee5s\u1ee5 Igbo',
      lang_code: 'ig',
      id: 'ig',
    },
  ],
  [
    'gn',
    {
      readable_name: 'Guaran\u00ed',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Ava\u00f1e\u1ebd',
      lang_code: 'gn',
      id: 'gn',
    },
  ],
  [
    'id',
    {
      readable_name: 'Indonesian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Bahasa Indonesia',
      lang_code: 'id',
      id: 'id',
    },
  ],
  [
    'su',
    {
      readable_name: 'Sundanese',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Basa Sunda',
      lang_code: 'su',
      id: 'su',
    },
  ],
  [
    'bi',
    {
      readable_name: 'Bislama',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Bislama',
      lang_code: 'bi',
      id: 'bi',
    },
  ],
  [
    'en-GB',
    {
      readable_name: 'English, Britain',
      lang_subcode: 'GB',
      lang_direction: 'ltr',
      native_name: 'British English',
      lang_code: 'en',
      id: 'en-GB',
    },
  ],
  [
    'bug',
    {
      readable_name: 'Buginese',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Buginese',
      lang_code: 'bug',
      id: 'bug',
    },
  ],
  [
    'ca',
    {
      readable_name: 'Catalan; Valencian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Catal\u00e0',
      lang_code: 'ca',
      id: 'ca',
    },
  ],
  [
    'ceb',
    {
      readable_name: 'Cebuano',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Cebuano',
      lang_code: 'ceb',
      id: 'ceb',
    },
  ],
  [
    'ch',
    {
      readable_name: 'Chamorro',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Chamoru',
      lang_code: 'ch',
      id: 'ch',
    },
  ],
  [
    'cho',
    {
      readable_name: 'Choctaw',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Choctaw',
      lang_code: 'cho',
      id: 'cho',
    },
  ],
  [
    'cy',
    {
      readable_name: 'Welsh',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Cymraeg',
      lang_code: 'cy',
      id: 'cy',
    },
  ],
  [
    'da',
    {
      readable_name: 'Danish',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Dansk',
      lang_code: 'da',
      id: 'da',
    },
  ],
  [
    'se',
    {
      readable_name: 'Northern Sami',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Davvis\u00e1megiella',
      lang_code: 'se',
      id: 'se',
    },
  ],
  [
    'de',
    {
      readable_name: 'German',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Deutsch',
      lang_code: 'de',
      id: 'de',
    },
  ],
  [
    'nv',
    {
      readable_name: 'Navajo; Navaho',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Din\u00e9 bizaad, Din\u00e9k\u02bceh\u01f0\u00ed',
      lang_code: 'nv',
      id: 'nv',
    },
  ],
  [
    'efi',
    {
      readable_name: 'Efik',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Efik',
      lang_code: 'efi',
      id: 'efi',
    },
  ],
  [
    'na',
    {
      readable_name: 'Nauru',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Ekakair\u0169 Naoero',
      lang_code: 'na',
      id: 'na',
    },
  ],
  [
    'en',
    {
      readable_name: 'English',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'English',
      lang_code: 'en',
      id: 'en',
    },
  ],
  [
    'es',
    {
      readable_name: 'Spanish',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Espa\u00f1ol',
      lang_code: 'es',
      id: 'es',
    },
  ],
  [
    'es-AR',
    {
      readable_name: 'Spanish, Argentina',
      lang_subcode: 'AR',
      lang_direction: 'ltr',
      native_name: 'Espa\u00f1ol (Argentina)',
      lang_code: 'es',
      id: 'es-AR',
    },
  ],
  [
    'es-ES',
    {
      readable_name: 'Spanish, Spain; Castilian',
      lang_subcode: 'ES',
      lang_direction: 'ltr',
      native_name: 'Espa\u00f1ol (Espa\u00f1a), Castellano',
      lang_code: 'es',
      id: 'es-ES',
    },
  ],
  [
    'es-MX',
    {
      readable_name: 'Spanish, Mexico',
      lang_subcode: 'MX',
      lang_direction: 'ltr',
      native_name: 'Espa\u00f1ol (Mexico)',
      lang_code: 'es',
      id: 'es-MX',
    },
  ],
  [
    'es-NI',
    {
      readable_name: 'Spanish, Nicaragua',
      lang_subcode: 'NI',
      lang_direction: 'ltr',
      native_name: 'Espa\u00f1ol (Nicaragua)',
      lang_code: 'es',
      id: 'es-NI',
    },
  ],
  [
    'eo',
    {
      readable_name: 'Esperanto',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Esperanto',
      lang_code: 'eo',
      id: 'eo',
    },
  ],
  [
    'ee',
    {
      readable_name: 'Ewe',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'E\u028begbe',
      lang_code: 'ee',
      id: 'ee',
    },
  ],
  [
    'fr-CA',
    {
      readable_name: 'French, Canada',
      lang_subcode: 'CA',
      lang_direction: 'ltr',
      native_name: 'Fran\u00e7ais (Canada)',
      lang_code: 'fr',
      id: 'fr-CA',
    },
  ],
  [
    'fr',
    {
      readable_name: 'French',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Fran\u00e7ais, langue fran\u00e7aise',
      lang_code: 'fr',
      id: 'fr',
    },
  ],
  [
    'fy',
    {
      readable_name: 'Western Frisian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Frysk',
      lang_code: 'fy',
      id: 'fy',
    },
  ],
  [
    'fy-NL',
    {
      readable_name: 'Frisian',
      lang_subcode: 'NL',
      lang_direction: 'ltr',
      native_name: 'Frysk',
      lang_code: 'fy',
      id: 'fy-NL',
    },
  ],
  [
    'ful',
    {
      readable_name: 'Fula; Fulah',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Fulfulde',
      lang_code: 'ful',
      id: 'ful',
    },
  ],
  [
    'fuv',
    {
      readable_name: 'Fulfulde Mbororo; Fulfulde Mbororoore',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Fulfulde',
      lang_code: 'fuv',
      id: 'fuv',
    },
  ],
  [
    'ff',
    {
      readable_name: 'Fula; Fulah; Pulaar; Pular',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Fulfulde, Pulaar, Pular',
      lang_code: 'ff',
      id: 'ff',
    },
  ],
  [
    'ga',
    {
      readable_name: 'Irish',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Gaeilge',
      lang_code: 'ga',
      id: 'ga',
    },
  ],
  [
    'gv',
    {
      readable_name: 'Manx',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Gaelg, Gailck',
      lang_code: 'gv',
      id: 'gv',
    },
  ],
  [
    'gl',
    {
      readable_name: 'Galician',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Galego',
      lang_code: 'gl',
      id: 'gl',
    },
  ],
  [
    'gd',
    {
      readable_name: 'Scottish Gaelic; Gaelic',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'G\u00e0idhlig',
      lang_code: 'gd',
      id: 'gd',
    },
  ],
  [
    'ki',
    {
      readable_name: 'Kikuyu; Gikuyu',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'G\u0129k\u0169y\u0169',
      lang_code: 'ki',
      id: 'ki',
    },
  ],
  [
    'kik',
    {
      readable_name: 'Kikuyu',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'G\u0129k\u0169y\u0169',
      lang_code: 'kik',
      id: 'kik',
    },
  ],
  [
    'hdy',
    {
      readable_name: 'Hadiyya; Hadiya; Adea; Adiya; Hadia',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Hadiyyisa',
      lang_code: 'hdy',
      id: 'hdy',
    },
  ],
  [
    'hau',
    {
      readable_name: 'Hausa',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Hausa, \u0647\u064e\u0648\u064f\u0633\u064e',
      lang_code: 'hau',
      id: 'hau',
    },
  ],
  [
    'ha',
    {
      readable_name: 'Hausa',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Hausa, \u0647\u064e\u0648\u064f\u0633\u064e',
      lang_code: 'ha',
      id: 'ha',
    },
  ],
  [
    'ho',
    {
      readable_name: 'Hiri Motu',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Hiri Motu',
      lang_code: 'ho',
      id: 'ho',
    },
  ],
  [
    'hrx',
    {
      readable_name: 'Hunsrik',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Hunsr\u00fcckisch, Hunsr\u00fcck, Hunsriker',
      lang_code: 'hrx',
      id: 'hrx',
    },
  ],
  [
    'io',
    {
      readable_name: 'Ido',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Ido',
      lang_code: 'io',
      id: 'io',
    },
  ],
  [
    'rw',
    {
      readable_name: 'Kinyarwanda',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Ikinyarwanda',
      lang_code: 'rw',
      id: 'rw',
    },
  ],
  [
    'ia',
    {
      readable_name: 'Interlingua',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Interlingua',
      lang_code: 'ia',
      id: 'ia',
    },
  ],
  [
    'it',
    {
      readable_name: 'Italian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Italiano',
      lang_code: 'it',
      id: 'it',
    },
  ],
  [
    'ik',
    {
      readable_name: 'Inupiaq',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'I\u00f1upiaq, I\u00f1upiatun',
      lang_code: 'ik',
      id: 'ik',
    },
  ],
  [
    'mh',
    {
      readable_name: 'Marshallese',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Kajin M\u0327aje\u013c',
      lang_code: 'mh',
      id: 'mh',
    },
  ],
  [
    'kr',
    {
      readable_name: 'Kanuri',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Kanuri',
      lang_code: 'kr',
      id: 'kr',
    },
  ],
  [
    'kw',
    {
      readable_name: 'Cornish',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Kernewek',
      lang_code: 'kw',
      id: 'kw',
    },
  ],
  [
    'kon',
    {
      readable_name: 'Kongo',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'KiKongo',
      lang_code: 'kon',
      id: 'kon',
    },
  ],
  [
    'kg',
    {
      readable_name: 'Kongo',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'KiKongo',
      lang_code: 'kg',
      id: 'kg',
    },
  ],
  [
    'swa',
    {
      readable_name: 'Swahili',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Kiswahili',
      lang_code: 'swa',
      id: 'swa',
    },
  ],
  [
    'sw',
    {
      readable_name: 'Swahili',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Kiswahili',
      lang_code: 'sw',
      id: 'sw',
    },
  ],
  [
    'ht',
    {
      readable_name: 'Haitian; Haitian Creole',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Krey\u00f2l ayisyen',
      lang_code: 'ht',
      id: 'ht',
    },
  ],
  [
    'kj',
    {
      readable_name: 'Kwanyama; Kuanyama',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Kuanyama',
      lang_code: 'kj',
      id: 'kj',
    },
  ],
  [
    'ku',
    {
      readable_name: 'Kurdish',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Kurd\u00ee, \u0643\u0648\u0631\u062f\u06cc\u200e',
      lang_code: 'ku',
      id: 'ku',
    },
  ],
  [
    'lkt',
    {
      readable_name: 'Lakhota; Lakotiyapi; Teton',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Lakhota',
      lang_code: 'lkt',
      id: 'lkt',
    },
  ],
  [
    'li',
    {
      readable_name: 'Limburgish; Limburgan; Limburger',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Limburgs',
      lang_code: 'li',
      id: 'li',
    },
  ],
  [
    'ln',
    {
      readable_name: 'Lingala',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Ling\u00e1la',
      lang_code: 'ln',
      id: 'ln',
    },
  ],
  [
    'lin',
    {
      readable_name: 'Lingala',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Ling\u00e1la',
      lang_code: 'lin',
      id: 'lin',
    },
  ],
  [
    'lua',
    {
      readable_name: 'Luba-Kasai',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Luba-Kasai, Tshiluba',
      lang_code: 'lua',
      id: 'lua',
    },
  ],
  [
    'lu',
    {
      readable_name: 'Luba-Katanga',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Luba-Katanga',
      lang_code: 'lu',
      id: 'lu',
    },
  ],
  [
    'lg',
    {
      readable_name: 'Luganda',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Luganda',
      lang_code: 'lg',
      id: 'lg',
    },
  ],
  [
    'myx',
    {
      readable_name: 'Masaaba; Bagisu',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Lumasaaba, Masaaba',
      lang_code: 'myx',
      id: 'myx',
    },
  ],
  [
    'xog',
    {
      readable_name: 'Soga',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Lusoga, Olusoga',
      lang_code: 'xog',
      id: 'xog',
    },
  ],
  [
    'lb',
    {
      readable_name: 'Luxembourgish; Letzeburgesch',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'L\u00ebtzebuergesch',
      lang_code: 'lb',
      id: 'lb',
    },
  ],
  [
    'hu',
    {
      readable_name: 'Hungarian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Magyar',
      lang_code: 'hu',
      id: 'hu',
    },
  ],
  [
    'mg',
    {
      readable_name: 'Malagasy',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Malagasy fiteny',
      lang_code: 'mg',
      id: 'mg',
    },
  ],
  [
    'mt',
    {
      readable_name: 'Maltese',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Malti',
      lang_code: 'mt',
      id: 'mt',
    },
  ],
  [
    'mul',
    {
      readable_name: 'Multiple languages',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Multiple languages',
      lang_code: 'mul',
      id: 'mul',
    },
  ],
  [
    'nl',
    {
      readable_name: 'Dutch',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Nederlands, Vlaams',
      lang_code: 'nl',
      id: 'nl',
    },
  ],
  [
    'tuv',
    {
      readable_name: 'Turkana; Turkwana; Buma; Bume',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: "Ng\u2019aturkana, Ng'aturkana",
      lang_code: 'tuv',
      id: 'tuv',
    },
  ],
  [
    'no',
    {
      readable_name: 'Norwegian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Norsk',
      lang_code: 'no',
      id: 'no',
    },
  ],
  [
    'nb',
    {
      readable_name: 'Norwegian Bokm\u00e5l',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Norsk bokm\u00e5l',
      lang_code: 'nb',
      id: 'nb',
    },
  ],
  [
    'nn',
    {
      readable_name: 'Norwegian Nynorsk',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Norsk nynorsk',
      lang_code: 'nn',
      id: 'nn',
    },
  ],
  [
    'oc',
    {
      readable_name: 'Occitan',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Occitan',
      lang_code: 'oc',
      id: 'oc',
    },
  ],
  [
    'lwg',
    {
      readable_name: 'Oluwanga; Oluhanga; Hanga; Kawanga',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Oluwanga',
      lang_code: 'lwg',
      id: 'lwg',
    },
  ],
  [
    'ie',
    {
      readable_name: 'Interlingue',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Originally called Occidental; then Interlingue after WWII',
      lang_code: 'ie',
      id: 'ie',
    },
  ],
  [
    'hz',
    {
      readable_name: 'Herero',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Otjiherero',
      lang_code: 'hz',
      id: 'hz',
    },
  ],
  [
    'ng',
    {
      readable_name: 'Ndonga',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Owambo',
      lang_code: 'ng',
      id: 'ng',
    },
  ],
  [
    'pms',
    {
      readable_name: 'Piedmontese',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Piemont\u00e8is',
      lang_code: 'pms',
      id: 'pms',
    },
  ],
  [
    'fil',
    {
      readable_name: 'Filipino',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Pilipino',
      lang_code: 'fil',
      id: 'fil',
    },
  ],
  [
    'pl',
    {
      readable_name: 'Polish',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Polski',
      lang_code: 'pl',
      id: 'pl',
    },
  ],
  [
    'pt',
    {
      readable_name: 'Portuguese',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Portugu\u00eas',
      lang_code: 'pt',
      id: 'pt',
    },
  ],
  [
    'pt-BR',
    {
      readable_name: 'Portuguese, Brazil',
      lang_subcode: 'BR',
      lang_direction: 'ltr',
      native_name: 'Portugu\u00eas (Brasil)',
      lang_code: 'pt',
      id: 'pt-BR',
    },
  ],
  [
    'pt-PT',
    {
      readable_name: 'Portuguese, Portugal',
      lang_subcode: 'PT',
      lang_direction: 'ltr',
      native_name: 'Portugu\u00eas (Portugal)',
      lang_code: 'pt',
      id: 'pt-PT',
    },
  ],
  [
    'ty',
    {
      readable_name: 'Tahitian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Reo Tahiti',
      lang_code: 'ty',
      id: 'ty',
    },
  ],
  [
    'que',
    {
      readable_name: 'Quechua',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Runa Simi',
      lang_code: 'que',
      id: 'que',
    },
  ],
  [
    'qu',
    {
      readable_name: 'Quechua',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Runa Simi, Kichwa',
      lang_code: 'qu',
      id: 'qu',
    },
  ],
  [
    'nyn',
    {
      readable_name: 'Nyankore; Nkole; Nyankole',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Runyankore',
      lang_code: 'nyn',
      id: 'nyn',
    },
  ],
  [
    'za',
    {
      readable_name: 'Zhuang; Chuang',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Sa\u026f cue\u014b\u0185, Saw cuengh',
      lang_code: 'za',
      id: 'za',
    },
  ],
  [
    'sco',
    {
      readable_name: 'Scots',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Scots',
      lang_code: 'sco',
      id: 'sco',
    },
  ],
  [
    'nso',
    {
      readable_name: 'Northern Sotho',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Sepedi, Sesotho sa Leboa, Pedi',
      lang_code: 'nso',
      id: 'nso',
    },
  ],
  [
    'st',
    {
      readable_name: 'Southern Sotho',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Sesotho',
      lang_code: 'st',
      id: 'st',
    },
  ],
  [
    'sot',
    {
      readable_name: 'Southern Sotho',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Sesotho',
      lang_code: 'sot',
      id: 'sot',
    },
  ],
  [
    'tsn',
    {
      readable_name: 'Tswana',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Setswana',
      lang_code: 'tsn',
      id: 'tsn',
    },
  ],
  [
    'tn',
    {
      readable_name: 'Tswana',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Setswana',
      lang_code: 'tn',
      id: 'tn',
    },
  ],
  [
    'sq',
    {
      readable_name: 'Albanian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Shqip',
      lang_code: 'sq',
      id: 'sq',
    },
  ],
  [
    'ss',
    {
      readable_name: 'Swati',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'SiSwati',
      lang_code: 'ss',
      id: 'ss',
    },
  ],
  [
    'sid',
    {
      readable_name: 'Sidamo; Sidaamu afii; Sidaama; Sidama',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Sidaamu Afoo',
      lang_code: 'sid',
      id: 'sid',
    },
  ],
  [
    'som',
    {
      readable_name: 'Somali',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Soomaaliga',
      lang_code: 'som',
      id: 'som',
    },
  ],
  [
    'so',
    {
      readable_name: 'Somali',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Soomaaliga, af Soomaali',
      lang_code: 'so',
      id: 'so',
    },
  ],
  [
    'sv-SE',
    {
      readable_name: 'Swedish',
      lang_subcode: 'SE',
      lang_direction: 'ltr',
      native_name: 'Svenska',
      lang_code: 'sv',
      id: 'sv-SE',
    },
  ],
  [
    'sv-FI',
    {
      readable_name: 'Swedish',
      lang_subcode: 'FI',
      lang_direction: 'ltr',
      native_name: 'Svenska',
      lang_code: 'sv',
      id: 'sv-FI',
    },
  ],
  [
    'be-tara',
    {
      readable_name: 'Belarusian, Classical Orthography',
      lang_subcode: 'tara',
      lang_direction: 'ltr',
      native_name:
        'Tara\u0161kievica, \u0442\u0430\u0440\u0430\u0448\u043a\u0435\u0432\u0456\u0446\u0430, \u0411\u0435\u043b\u0430\u0440\u0443\u0441\u043a\u0430\u044f \u043a\u043b\u044f\u0441\u044b\u0447\u043d\u044b \u043f\u0440\u0430\u0432\u0430\u043f\u0456\u0441',
      lang_code: 'be',
      id: 'be-tara',
    },
  ],
  [
    'vi',
    {
      readable_name: 'Vietnamese',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Ti\u1ebfng Vi\u1ec7t',
      lang_code: 'vi',
      id: 'vi',
    },
  ],
  [
    've',
    {
      readable_name: 'Venda',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Tshiven\u1e13a, Tshivenda',
      lang_code: 've',
      id: 've',
    },
  ],
  [
    'tw',
    {
      readable_name: 'Twi',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Twi',
      lang_code: 'tw',
      id: 'tw',
    },
  ],
  [
    'tk',
    {
      readable_name: 'Turkmen',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'T\u00fcrkmen, \u0422\u04af\u0440\u043a\u043c\u0435\u043d',
      lang_code: 'tk',
      id: 'tk',
    },
  ],
  [
    'tr',
    {
      readable_name: 'Turkish',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'T\u00fcrk\u00e7e',
      lang_code: 'tr',
      id: 'tr',
    },
  ],
  [
    'und',
    {
      readable_name: 'Undetermined',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Undetermined',
      lang_code: 'und',
      id: 'und',
    },
  ],
  [
    'ur-PK',
    {
      readable_name: 'Urdu',
      lang_subcode: 'PK',
      lang_direction: 'rtl',
      native_name: 'Urdu',
      lang_code: 'ur',
      id: 'ur-PK',
    },
  ],
  [
    'ug',
    {
      readable_name: 'Uighur; Uyghur',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Uy\u01a3urq\u0259, \u0626\u06c7\u064a\u063a\u06c7\u0631\u0686\u06d5\u200e',
      lang_code: 'ug',
      id: 'ug',
    },
  ],
  [
    'vo',
    {
      readable_name: 'Volap\u00fck',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Volap\u00fck',
      lang_code: 'vo',
      id: 'vo',
    },
  ],
  [
    'wa',
    {
      readable_name: 'Walloon',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Walon',
      lang_code: 'wa',
      id: 'wa',
    },
  ],
  [
    'tl',
    {
      readable_name: 'Tagalog',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Wikang Tagalog',
      lang_code: 'tl',
      id: 'tl',
    },
  ],
  [
    'wal',
    {
      readable_name: 'Wolaytta; Borodda; Uba; Ometo',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Wolaytta',
      lang_code: 'wal',
      id: 'wal',
    },
  ],
  [
    'wol',
    {
      readable_name: 'Wolof',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Wollof',
      lang_code: 'wol',
      id: 'wol',
    },
  ],
  [
    'wo',
    {
      readable_name: 'Wolof',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Wollof',
      lang_code: 'wo',
      id: 'wo',
    },
  ],
  [
    'ts',
    {
      readable_name: 'Tsonga',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Xitsonga',
      lang_code: 'ts',
      id: 'ts',
    },
  ],
  [
    'yo',
    {
      readable_name: 'Yoruba',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Yor\u00f9b\u00e1',
      lang_code: 'yo',
      id: 'yo',
    },
  ],
  [
    'yor',
    {
      readable_name: 'Yoruba',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'Yor\u00f9b\u00e1',
      lang_code: 'yor',
      id: 'yor',
    },
  ],
  [
    'ae',
    {
      readable_name: 'Avestan',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'avesta',
      lang_code: 'ae',
      id: 'ae',
    },
  ],
  [
    'ay',
    {
      readable_name: 'Aymara',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'aymar aru',
      lang_code: 'ay',
      id: 'ay',
    },
  ],
  [
    'az',
    {
      readable_name: 'Azerbaijani',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'az\u0259rbaycan dili',
      lang_code: 'az',
      id: 'az',
    },
  ],
  [
    'ms',
    {
      readable_name: 'Malay',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'bahasa Melayu, \u0628\u0647\u0627\u0633 \u0645\u0644\u0627\u064a\u0648\u200e',
      lang_code: 'ms',
      id: 'ms',
    },
  ],
  [
    'bm',
    {
      readable_name: 'Bambara',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'bamanankan',
      lang_code: 'bm',
      id: 'bm',
    },
  ],
  [
    'jv',
    {
      readable_name: 'Javanese',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'basa Jawa',
      lang_code: 'jv',
      id: 'jv',
    },
  ],
  [
    'bs',
    {
      readable_name: 'Bosnian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'bosanski jezik',
      lang_code: 'bs',
      id: 'bs',
    },
  ],
  [
    'br',
    {
      readable_name: 'Breton',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'brezhoneg',
      lang_code: 'br',
      id: 'br',
    },
  ],
  [
    'nya',
    {
      readable_name: 'Chichewa',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'chiChe\u0175a',
      lang_code: 'nya',
      id: 'nya',
    },
  ],
  [
    'ny',
    {
      readable_name: 'Chichewa; Chewa; Nyanja',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'chiChe\u0175a, chinyanja',
      lang_code: 'ny',
      id: 'ny',
    },
  ],
  [
    'sn',
    {
      readable_name: 'Shona',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'chiShona',
      lang_code: 'sn',
      id: 'sn',
    },
  ],
  [
    'sna',
    {
      readable_name: 'Shona',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'chiShona',
      lang_code: 'sna',
      id: 'sna',
    },
  ],
  [
    'co',
    {
      readable_name: 'Corsican',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'corsu, lingua corsa',
      lang_code: 'co',
      id: 'co',
    },
  ],
  [
    'et',
    {
      readable_name: 'Estonian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'eesti, eesti keel',
      lang_code: 'et',
      id: 'et',
    },
  ],
  [
    'eu',
    {
      readable_name: 'Basque',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'euskara, euskera',
      lang_code: 'eu',
      id: 'eu',
    },
  ],
  [
    'to',
    {
      readable_name: 'Tonga (Tonga Islands)',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'faka Tonga',
      lang_code: 'to',
      id: 'to',
    },
  ],
  [
    'mlg',
    {
      readable_name: 'Malagasy',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'fiteny malagasy',
      lang_code: 'mlg',
      id: 'mlg',
    },
  ],
  [
    'fo',
    {
      readable_name: 'Faroese',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'f\u00f8royskt',
      lang_code: 'fo',
      id: 'fo',
    },
  ],
  [
    'sm',
    {
      readable_name: 'Samoan',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'gagana faa Samoa',
      lang_code: 'sm',
      id: 'sm',
    },
  ],
  [
    'hr',
    {
      readable_name: 'Croatian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'hrvatski',
      lang_code: 'hr',
      id: 'hr',
    },
  ],
  [
    'nd',
    {
      readable_name: 'North Ndebele',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'isiNdebele',
      lang_code: 'nd',
      id: 'nd',
    },
  ],
  [
    'nr',
    {
      readable_name: 'South Ndebele',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'isiNdebele',
      lang_code: 'nr',
      id: 'nr',
    },
  ],
  [
    'xho',
    {
      readable_name: 'Xhosa',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'isiXhosa',
      lang_code: 'xho',
      id: 'xho',
    },
  ],
  [
    'xh',
    {
      readable_name: 'Xhosa',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'isiXhosa',
      lang_code: 'xh',
      id: 'xh',
    },
  ],
  [
    'zul',
    {
      readable_name: 'Zulu',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'isiZulu',
      lang_code: 'zul',
      id: 'zul',
    },
  ],
  [
    'kl',
    {
      readable_name: 'Kalaallisut, Greenlandic',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'kalaallisut, kalaallit oqaasii',
      lang_code: 'kl',
      id: 'kl',
    },
  ],
  [
    'rn',
    {
      readable_name: 'Kirundi',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'kiRundi',
      lang_code: 'rn',
      id: 'rn',
    },
  ],
  [
    'la',
    {
      readable_name: 'Latin',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'latine, lingua latina',
      lang_code: 'la',
      id: 'la',
    },
  ],
  [
    'lv',
    {
      readable_name: 'Latvian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'latvie\u0161u valoda',
      lang_code: 'lv',
      id: 'lv',
    },
  ],
  [
    'lt',
    {
      readable_name: 'Lithuanian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'lietuvi\u0173 kalba',
      lang_code: 'lt',
      id: 'lt',
    },
  ],
  [
    'ro',
    {
      readable_name: 'Romanian; Moldavian; Moldovan',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'rom\u00e2n\u0103',
      lang_code: 'ro',
      id: 'ro',
    },
  ],
  [
    'rm',
    {
      readable_name: 'Romansh',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'rumantsch grischun',
      lang_code: 'rm',
      id: 'rm',
    },
  ],
  [
    'sc',
    {
      readable_name: 'Sardinian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'sardu',
      lang_code: 'sc',
      id: 'sc',
    },
  ],
  [
    'sk',
    {
      readable_name: 'Slovak',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'sloven\u010dina',
      lang_code: 'sk',
      id: 'sk',
    },
  ],
  [
    'sl',
    {
      readable_name: 'Slovene',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'sloven\u0161\u010dina',
      lang_code: 'sl',
      id: 'sl',
    },
  ],
  [
    'fi',
    {
      readable_name: 'Finnish',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'suomi, suomen kieli',
      lang_code: 'fi',
      id: 'fi',
    },
  ],
  [
    'sv',
    {
      readable_name: 'Swedish',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'svenska',
      lang_code: 'sv',
      id: 'sv',
    },
  ],
  [
    'mi',
    {
      readable_name: 'M\u0101ori',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'te reo M\u0101ori',
      lang_code: 'mi',
      id: 'mi',
    },
  ],
  [
    'fj',
    {
      readable_name: 'Fijian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'vosa Vakaviti',
      lang_code: 'fj',
      id: 'fj',
    },
  ],
  [
    'sg',
    {
      readable_name: 'Sango',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: 'y\u00e2ng\u00e2 t\u00ee s\u00e4ng\u00f6',
      lang_code: 'sg',
      id: 'sg',
    },
  ],
  [
    'uz',
    {
      readable_name: 'Uzbek',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name:
        'zbek, \u040e\u0437\u0431\u0435\u043a, \u0623\u06c7\u0632\u0628\u06d0\u0643\u200e',
      lang_code: 'uz',
      id: 'uz',
    },
  ],
  [
    'is',
    {
      readable_name: 'Icelandic',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u00cdslenska',
      lang_code: 'is',
      id: 'is',
    },
  ],
  [
    'cs',
    {
      readable_name: 'Czech',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u010desky, \u010de\u0161tina',
      lang_code: 'cs',
      id: 'cs',
    },
  ],
  [
    'el',
    {
      readable_name: 'Greek, Modern',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0395\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac',
      lang_code: 'el',
      id: 'el',
    },
  ],
  [
    'be',
    {
      readable_name: 'Belarusian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0411\u0435\u043b\u0430\u0440\u0443\u0441\u043a\u0430\u044f',
      lang_code: 'be',
      id: 'be',
    },
  ],
  [
    'av',
    {
      readable_name: 'Avaric',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name:
        '\u0430\u0432\u0430\u0440 \u043c\u0430\u0446\u04c0, \u043c\u0430\u0433\u04c0\u0430\u0440\u0443\u043b \u043c\u0430\u0446\u04c0',
      lang_code: 'av',
      id: 'av',
    },
  ],
  [
    'ab',
    {
      readable_name: 'Abkhaz',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0430\u04a7\u0441\u0443\u0430',
      lang_code: 'ab',
      id: 'ab',
    },
  ],
  [
    'ba',
    {
      readable_name: 'Bashkir',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0431\u0430\u0448\u04a1\u043e\u0440\u0442 \u0442\u0435\u043b\u0435',
      lang_code: 'ba',
      id: 'ba',
    },
  ],
  [
    'bg',
    {
      readable_name: 'Bulgarian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name:
        '\u0431\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438 \u0435\u0437\u0438\u043a',
      lang_code: 'bg',
      id: 'bg',
    },
  ],
  [
    'os',
    {
      readable_name: 'Ossetian; Ossetic',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0438\u0440\u043e\u043d \u00e6\u0432\u0437\u0430\u0433',
      lang_code: 'os',
      id: 'os',
    },
  ],
  [
    'kv',
    {
      readable_name: 'Komi',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u043a\u043e\u043c\u0438 \u043a\u044b\u0432',
      lang_code: 'kv',
      id: 'kv',
    },
  ],
  [
    'ky',
    {
      readable_name: 'Kirghiz; Kyrgyz',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u043a\u044b\u0440\u0433\u044b\u0437 \u0442\u0438\u043b\u0438',
      lang_code: 'ky',
      id: 'ky',
    },
  ],
  [
    'mk',
    {
      readable_name: 'Macedonian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name:
        '\u043c\u0430\u043a\u0435\u0434\u043e\u043d\u0441\u043a\u0438 \u0458\u0430\u0437\u0438\u043a',
      lang_code: 'mk',
      id: 'mk',
    },
  ],
  [
    'mn',
    {
      readable_name: 'Mongolian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u043c\u043e\u043d\u0433\u043e\u043b',
      lang_code: 'mn',
      id: 'mn',
    },
  ],
  [
    'ce',
    {
      readable_name: 'Chechen',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u043d\u043e\u0445\u0447\u0438\u0439\u043d \u043c\u043e\u0442\u0442',
      lang_code: 'ce',
      id: 'ce',
    },
  ],
  [
    'rue',
    {
      readable_name: 'Rusyn',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name:
        '\u0440\u0443\u0441\u0438\u043d\u044c\u0441\u043a\u044b\u0439 \u044f\u0437\u044b\u043a',
      lang_code: 'rue',
      id: 'rue',
    },
  ],
  [
    'ru',
    {
      readable_name: 'Russian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0440\u0443\u0441\u0441\u043a\u0438\u0439 \u044f\u0437\u044b\u043a',
      lang_code: 'ru',
      id: 'ru',
    },
  ],
  [
    'sr-LATN',
    {
      readable_name: 'Serbian, Latin',
      lang_subcode: 'LATN',
      lang_direction: 'ltr',
      native_name: '\u0441\u0440\u043f\u0441\u043a\u0438 \u0458\u0435\u0437\u0438\u043a',
      lang_code: 'sr',
      id: 'sr-LATN',
    },
  ],
  [
    'sr',
    {
      readable_name: 'Serbian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0441\u0440\u043f\u0441\u043a\u0438 \u0458\u0435\u0437\u0438\u043a',
      lang_code: 'sr',
      id: 'sr',
    },
  ],
  [
    'sr-CS',
    {
      readable_name: 'Serbian, Cyrillic',
      lang_subcode: 'CS',
      lang_direction: 'ltr',
      native_name: '\u0441\u0440\u043f\u0441\u043a\u0438 \u0458\u0435\u0437\u0438\u043a',
      lang_code: 'sr',
      id: 'sr-CS',
    },
  ],
  [
    'tt',
    {
      readable_name: 'Tatar',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name:
        '\u0442\u0430\u0442\u0430\u0440\u0447\u0430, tatar\u00e7a, \u062a\u0627\u062a\u0627\u0631\u0686\u0627\u200e',
      lang_code: 'tt',
      id: 'tt',
    },
  ],
  [
    'tg',
    {
      readable_name: 'Tajik',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name:
        '\u0442\u043e\u04b7\u0438\u043a\u04e3, to\u011fik\u012b, \u062a\u0627\u062c\u06cc\u06a9\u06cc\u200e',
      lang_code: 'tg',
      id: 'tg',
    },
  ],
  [
    'uk',
    {
      readable_name: 'Ukrainian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0443\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430',
      lang_code: 'uk',
      id: 'uk',
    },
  ],
  [
    'cv',
    {
      readable_name: 'Chuvash',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0447\u04d1\u0432\u0430\u0448 \u0447\u04d7\u043b\u0445\u0438',
      lang_code: 'cv',
      id: 'cv',
    },
  ],
  [
    'cu',
    {
      readable_name:
        'Old Church Slavonic; Church Slavic; Church Slavonic; Old Bulgarian; Old Slavonic',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name:
        '\u0469\u0437\u044b\u043a\u044a \u0441\u043b\u043e\u0432\u0463\u043d\u044c\u0441\u043a\u044a',
      lang_code: 'cu',
      id: 'cu',
    },
  ],
  [
    'kk',
    {
      readable_name: 'Kazakh',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u049a\u0430\u0437\u0430\u049b \u0442\u0456\u043b\u0456',
      lang_code: 'kk',
      id: 'kk',
    },
  ],
  [
    'hy',
    {
      readable_name: 'Armenian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0540\u0561\u0575\u0565\u0580\u0565\u0576',
      lang_code: 'hy',
      id: 'hy',
    },
  ],
  [
    'yi',
    {
      readable_name: 'Yiddish',
      lang_subcode: null,
      lang_direction: 'rtl',
      native_name: '\u05d9\u05d9\u05b4\u05d3\u05d9\u05e9',
      lang_code: 'yi',
      id: 'yi',
    },
  ],
  [
    'he',
    {
      readable_name: 'Hebrew (modern)',
      lang_subcode: null,
      lang_direction: 'rtl',
      native_name: '\u05e2\u05d1\u05e8\u05d9\u05ea',
      lang_code: 'he',
      id: 'he',
    },
  ],
  [
    'ur',
    {
      readable_name: 'Urdu',
      lang_subcode: null,
      lang_direction: 'rtl',
      native_name: '\u0627\u0631\u062f\u0648',
      lang_code: 'ur',
      id: 'ur',
    },
  ],
  [
    'ar',
    {
      readable_name: 'Arabic',
      lang_subcode: null,
      lang_direction: 'rtl',
      native_name: '\u0627\u0644\u0639\u0631\u0628\u064a\u0629',
      lang_code: 'ar',
      id: 'ar',
    },
  ],
  [
    'arq',
    {
      readable_name: 'Algerian; Darja',
      lang_subcode: null,
      lang_direction: 'rtl',
      native_name: '\u062f\u0632\u064a\u0631\u064a\u0629',
      lang_code: 'arq',
      id: 'arq',
    },
  ],
  [
    'fa',
    {
      readable_name: 'Persian',
      lang_subcode: null,
      lang_direction: 'rtl',
      native_name: '\u0641\u0627\u0631\u0633\u06cc',
      lang_code: 'fa',
      id: 'fa',
    },
  ],
  [
    'ps',
    {
      readable_name: 'Pashto; Pushto',
      lang_subcode: null,
      lang_direction: 'rtl',
      native_name: '\u067e\u069a\u062a\u0648',
      lang_code: 'ps',
      id: 'ps',
    },
  ],
  [
    'dv',
    {
      readable_name: 'Divehi; Dhivehi; Maldivian',
      lang_subcode: null,
      lang_direction: 'rtl',
      native_name: '\u078b\u07a8\u0788\u07ac\u0780\u07a8',
      lang_code: 'dv',
      id: 'dv',
    },
  ],
  [
    'ks',
    {
      readable_name: 'Kashmiri',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name:
        '\u0915\u0936\u094d\u092e\u0940\u0930\u0940, \u0643\u0634\u0645\u064a\u0631\u064a\u200e',
      lang_code: 'ks',
      id: 'ks',
    },
  ],
  [
    'ne-NP',
    {
      readable_name: 'Nepali',
      lang_subcode: 'NP',
      lang_direction: 'ltr',
      native_name: '\u0928\u0947\u092a\u093e\u0932\u0940',
      lang_code: 'ne',
      id: 'ne-NP',
    },
  ],
  [
    'ne',
    {
      readable_name: 'Nepali',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0928\u0947\u092a\u093e\u0932\u0940',
      lang_code: 'ne',
      id: 'ne',
    },
  ],
  [
    'pi',
    {
      readable_name: 'P\u0101li',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u092a\u093e\u0934\u093f',
      lang_code: 'pi',
      id: 'pi',
    },
  ],
  [
    'bh',
    {
      readable_name: 'Bihari',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u092d\u094b\u091c\u092a\u0941\u0930\u0940',
      lang_code: 'bh',
      id: 'bh',
    },
  ],
  [
    'bho',
    {
      readable_name: 'Bhojpuri; Bajpuri; Bhojapuri',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u092d\u094b\u091c\u092a\u0941\u0930\u0940',
      lang_code: 'bho',
      id: 'bho',
    },
  ],
  [
    'mr',
    {
      readable_name: 'Marathi (Mar\u0101\u1e6dh\u012b)',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u092e\u0930\u093e\u0920\u0940',
      lang_code: 'mr',
      id: 'mr',
    },
  ],
  [
    'mwr',
    {
      readable_name: 'Marwari; Marwadi',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name:
        '\u092e\u093e\u0930\u0935\u093e\u0921\u093c\u0940, \u0645\u0627\u0631\u0648\u0627\u0691\u06cc',
      lang_code: 'mwr',
      id: 'mwr',
    },
  ],
  [
    'sa',
    {
      readable_name: 'Sanskrit (Sa\u1e41sk\u1e5bta)',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0938\u0902\u0938\u094d\u0915\u0943\u0924\u092e\u094d',
      lang_code: 'sa',
      id: 'sa',
    },
  ],
  [
    'sd',
    {
      readable_name: 'Sindhi',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name:
        '\u0938\u093f\u0928\u094d\u0927\u0940, \u0633\u0646\u068c\u064a\u060c \u0633\u0646\u062f\u06be\u06cc\u200e',
      lang_code: 'sd',
      id: 'sd',
    },
  ],
  [
    'hi',
    {
      readable_name: 'Hindi',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0939\u093f\u0928\u094d\u0926\u0940, \u0939\u093f\u0902\u0926\u0940',
      lang_code: 'hi',
      id: 'hi',
    },
  ],
  [
    'as',
    {
      readable_name: 'Assamese',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0985\u09b8\u09ae\u09c0\u09af\u09bc\u09be',
      lang_code: 'as',
      id: 'as',
    },
  ],
  [
    'bn',
    {
      readable_name: 'Bengali',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u09ac\u09be\u0982\u09b2\u09be',
      lang_code: 'bn',
      id: 'bn',
    },
  ],
  [
    'pnb',
    {
      readable_name: 'Punjabi',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0a2a\u0a70\u0a1c\u0a3e\u0a2c\u0a40',
      lang_code: 'pnb',
      id: 'pnb',
    },
  ],
  [
    'pa',
    {
      readable_name: 'Panjabi; Punjabi',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name:
        '\u0a2a\u0a70\u0a1c\u0a3e\u0a2c\u0a40, \u067e\u0646\u062c\u0627\u0628\u06cc\u200e',
      lang_code: 'pa',
      id: 'pa',
    },
  ],
  [
    'gu',
    {
      readable_name: 'Gujarati',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0a97\u0ac1\u0a9c\u0ab0\u0abe\u0aa4\u0ac0',
      lang_code: 'gu',
      id: 'gu',
    },
  ],
  [
    'or',
    {
      readable_name: 'Oriya',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0b13\u0b21\u0b3c\u0b3f\u0b06',
      lang_code: 'or',
      id: 'or',
    },
  ],
  [
    'ta',
    {
      readable_name: 'Tamil',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0ba4\u0bae\u0bbf\u0bb4\u0bcd',
      lang_code: 'ta',
      id: 'ta',
    },
  ],
  [
    'te',
    {
      readable_name: 'Telugu',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0c24\u0c46\u0c32\u0c41\u0c17\u0c41',
      lang_code: 'te',
      id: 'te',
    },
  ],
  [
    'kn',
    {
      readable_name: 'Kannada',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0c95\u0ca8\u0ccd\u0ca8\u0ca1',
      lang_code: 'kn',
      id: 'kn',
    },
  ],
  [
    'ml',
    {
      readable_name: 'Malayalam',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0d2e\u0d32\u0d2f\u0d3e\u0d33\u0d02',
      lang_code: 'ml',
      id: 'ml',
    },
  ],
  [
    'si',
    {
      readable_name: 'Sinhala; Sinhalese',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0dc3\u0dd2\u0d82\u0dc4\u0dbd',
      lang_code: 'si',
      id: 'si',
    },
  ],
  [
    'th',
    {
      readable_name: 'Thai',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0e44\u0e17\u0e22',
      lang_code: 'th',
      id: 'th',
    },
  ],
  [
    'lo',
    {
      readable_name: 'Lao',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0e9e\u0eb2\u0eaa\u0eb2\u0ea5\u0eb2\u0ea7',
      lang_code: 'lo',
      id: 'lo',
    },
  ],
  [
    'bo',
    {
      readable_name: 'Tibetan Standard; Tibetan, Central',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u0f56\u0f7c\u0f51\u0f0b\u0f61\u0f72\u0f42',
      lang_code: 'bo',
      id: 'bo',
    },
  ],
  [
    'my',
    {
      readable_name: 'Burmese',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u1017\u1019\u102c\u1005\u102c',
      lang_code: 'my',
      id: 'my',
    },
  ],
  [
    'ka',
    {
      readable_name: 'Georgian',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u10e5\u10d0\u10e0\u10d7\u10e3\u10da\u10d8',
      lang_code: 'ka',
      id: 'ka',
    },
  ],
  [
    'tir',
    {
      readable_name: 'Tigrinya',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u1275\u130d\u122d\u129b',
      lang_code: 'tir',
      id: 'tir',
    },
  ],
  [
    'ti',
    {
      readable_name: 'Tigrinya',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u1275\u130d\u122d\u129b',
      lang_code: 'ti',
      id: 'ti',
    },
  ],
  [
    'am',
    {
      readable_name: 'Amharic',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u12a0\u121b\u122d\u129b',
      lang_code: 'am',
      id: 'am',
    },
  ],
  [
    'iu',
    {
      readable_name: 'Inuktitut',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u1403\u14c4\u1483\u144e\u1450\u1466',
      lang_code: 'iu',
      id: 'iu',
    },
  ],
  [
    'oji',
    {
      readable_name: 'Ojibwe',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u140a\u14c2\u1511\u14c8\u142f\u14a7\u140e\u14d0',
      lang_code: 'oji',
      id: 'oji',
    },
  ],
  [
    'oj',
    {
      readable_name: 'Ojibwe; Ojibwa',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u140a\u14c2\u1511\u14c8\u142f\u14a7\u140e\u14d0',
      lang_code: 'oj',
      id: 'oj',
    },
  ],
  [
    'cr',
    {
      readable_name: 'Cree',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u14c0\u1426\u1403\u152d\u140d\u140f\u1423',
      lang_code: 'cr',
      id: 'cr',
    },
  ],
  [
    'km',
    {
      readable_name: 'Khmer',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u1797\u17b6\u179f\u17b6\u1781\u17d2\u1798\u17c2\u179a',
      lang_code: 'km',
      id: 'km',
    },
  ],
  [
    'zh-CN',
    {
      readable_name: 'Chinese, Simplified',
      lang_subcode: 'CN',
      lang_direction: 'ltr',
      native_name: '\u4e2d\u56fd\u5927\u9646',
      lang_code: 'zh',
      id: 'zh-CN',
    },
  ],
  [
    'zh',
    {
      readable_name: 'Chinese',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\u4e2d\u6587, \u6c49\u8bed, \u6f22\u8a9e',
      lang_code: 'zh',
      id: 'zh',
    },
  ],
  [
    'ja',
    {
      readable_name: 'Japanese',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name:
        '\u65e5\u672c\u8a9e (\u306b\u307b\u3093\u3054\uff0f\u306b\u3063\u307d\u3093\u3054)',
      lang_code: 'ja',
      id: 'ja',
    },
  ],
  [
    'zh-Hant',
    {
      readable_name: 'Chinese, Traditional',
      lang_subcode: 'Hant',
      lang_direction: 'ltr',
      native_name: '\u6f22\u8a9e (\u7e41\u9ad4\u5b57)',
      lang_code: 'zh',
      id: 'zh-Hant',
    },
  ],
  [
    'zh-TW',
    {
      readable_name: 'Chinese, Taiwan',
      lang_subcode: 'TW',
      lang_direction: 'ltr',
      native_name: '\u6f22\u8a9e (\u81fa\u7063)',
      lang_code: 'zh',
      id: 'zh-TW',
    },
  ],
  [
    'ii',
    {
      readable_name: 'Nuosu',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name: '\ua188\ua320\ua4bf Nuosuhxop',
      lang_code: 'ii',
      id: 'ii',
    },
  ],
  [
    'ko',
    {
      readable_name: 'Korean',
      lang_subcode: null,
      lang_direction: 'ltr',
      native_name:
        '\ud55c\uad6d\uc5b4 (\u97d3\u570b\u8a9e), \uc870\uc120\ub9d0 (\u671d\u9bae\u8a9e)',
      lang_code: 'ko',
      id: 'ko',
    },
  ],
]);

export default LanguagesMap;

export const LanguagesList = Array.from(LanguagesMap.values());
