// Disabled because jest-dom matchers (toHaveAttribute/toHaveTextContent) are designed for
// HTML and do not work reliably on strict XML elements generated by serialization.
/* eslint-disable jest-dom/prefer-to-have-attribute, jest-dom/prefer-to-have-text-content */
import AreaMapping from '../../declarations/areaMapping.js';
import { QTIDeclaration } from '../../QTIDeclaration.js';
import { CAPABILITY } from '../../declarations/index.js';
import { parseXML, reparse } from '../testUtils.js';
import { AREA_MAPPING_WITH_BOUNDS_XML, AREA_MAPPING_XML } from './fixtures.js';

function makeDeclaration() {
  return new QTIDeclaration({ identifier: 'RESPONSE', baseType: 'point', cardinality: 'single' });
}

function parseAreaMappingXml(xmlString) {
  return parseXML(xmlString).querySelector('qti-area-mapping');
}

describe('AreaMapping', () => {
  describe('constructor', () => {
    it('stores the provided data', () => {
      const data = { defaultValue: 0, lowerBound: null, upperBound: null, entries: [] };
      const am = new AreaMapping(data, makeDeclaration());
      expect(am.get()).toEqual(data);
    });
  });

  describe('fromXML', () => {
    it('parses default-value', () => {
      const node = parseAreaMappingXml(AREA_MAPPING_XML);
      const am = AreaMapping.fromXML(node, makeDeclaration());
      expect(am.get().defaultValue).toBe(0);
    });

    it('parses lower-bound and upper-bound', () => {
      const node = parseAreaMappingXml(AREA_MAPPING_WITH_BOUNDS_XML);
      const am = AreaMapping.fromXML(node, makeDeclaration());
      expect(am.get().lowerBound).toBe(-2);
      expect(am.get().upperBound).toBe(3);
    });

    it('sets bounds to null when absent', () => {
      const node = parseAreaMappingXml(AREA_MAPPING_XML);
      const am = AreaMapping.fromXML(node, makeDeclaration());
      expect(am.get().lowerBound).toBeNull();
      expect(am.get().upperBound).toBeNull();
    });

    it('parses area entries', () => {
      const node = parseAreaMappingXml(AREA_MAPPING_XML);
      const am = AreaMapping.fromXML(node, makeDeclaration());
      expect(am.get().entries).toHaveLength(2);
    });

    it('stores shape as string', () => {
      const node = parseAreaMappingXml(AREA_MAPPING_XML);
      const am = AreaMapping.fromXML(node, makeDeclaration());
      expect(am.get().entries[0].shape).toBe('circle');
      expect(am.get().entries[1].shape).toBe('rect');
    });

    it('stores coords as an opaque string (not parsed)', () => {
      const node = parseAreaMappingXml(AREA_MAPPING_XML);
      const am = AreaMapping.fromXML(node, makeDeclaration());
      // Opaque string — not converted to numbers
      expect(am.get().entries[0].coords).toBe('100,100,50');
      expect(typeof am.get().entries[0].coords).toBe('string');
    });

    it('parses mappedValue as a number', () => {
      const node = parseAreaMappingXml(AREA_MAPPING_XML);
      const am = AreaMapping.fromXML(node, makeDeclaration());
      expect(am.get().entries[0].mappedValue).toBe(1);
      expect(am.get().entries[1].mappedValue).toBe(0.5);
    });

    it('registers itself as AREA_MAPPING capability', () => {
      const node = parseAreaMappingXml(AREA_MAPPING_XML);
      const declaration = makeDeclaration();
      AreaMapping.fromXML(node, declaration);
      expect(declaration._capabilities[CAPABILITY.AREA_MAPPING]).toBeDefined();
      expect(declaration.areaMapping).not.toBeNull();
    });
  });

  describe('getXML', () => {
    it('produces a qti-area-mapping element', () => {
      const data = { defaultValue: 0, lowerBound: null, upperBound: null, entries: [] };
      expect(new AreaMapping(data, makeDeclaration()).getXML().tagName).toBe('qti-area-mapping');
    });

    it('emits qti-area-map-entry children', () => {
      const data = {
        defaultValue: 0,
        lowerBound: null,
        upperBound: null,
        entries: [{ shape: 'circle', coords: '100,100,50', mappedValue: 1 }],
      };
      const node = new AreaMapping(data, makeDeclaration()).getXML();
      const entry = node.querySelector('qti-area-map-entry');
      expect(entry.getAttribute('shape')).toBe('circle');
      expect(entry.getAttribute('coords')).toBe('100,100,50');
      expect(entry.getAttribute('mapped-value')).toBe('1');
    });

    it('preserves coords exactly on round-trip (no float reformatting)', () => {
      const node = parseAreaMappingXml(AREA_MAPPING_WITH_BOUNDS_XML);
      const am = AreaMapping.fromXML(node, makeDeclaration());
      const entry = am.getXML().querySelector('qti-area-map-entry');
      expect(entry.getAttribute('coords')).toBe('10,10,50,10,50,50');
    });

    it('round-trips fromXML → getXML', () => {
      const node = parseAreaMappingXml(AREA_MAPPING_XML);
      const am = AreaMapping.fromXML(node, makeDeclaration());
      const out = am.getXML();
      expect(out.tagName).toBe('qti-area-mapping');
      const entry = out.querySelector('qti-area-map-entry');
      expect(entry.getAttribute('shape')).toBe('circle');
      expect(entry.getAttribute('coords')).toBe('100,100,50');
      expect(entry.getAttribute('mapped-value')).toBe('1');
    });
  });

  describe('full XML output (QTI compatibility)', () => {
    it('serializes to well-formed XML that re-parses without error', () => {
      const am = AreaMapping.fromXML(parseAreaMappingXml(AREA_MAPPING_XML), makeDeclaration());
      expect(() => reparse(am.getXML())).not.toThrow();
    });

    it('re-parsed XML has qti-area-mapping root tag', () => {
      const reparsed = reparse(
        AreaMapping.fromXML(parseAreaMappingXml(AREA_MAPPING_XML), makeDeclaration()).getXML(),
      );
      expect(reparsed.tagName).toBe('qti-area-mapping');
    });

    it('re-parsed XML has correct number of qti-area-map-entry children', () => {
      const reparsed = reparse(
        AreaMapping.fromXML(parseAreaMappingXml(AREA_MAPPING_XML), makeDeclaration()).getXML(),
      );
      expect(reparsed.querySelectorAll('qti-area-map-entry').length).toBe(2);
    });

    it('re-parsed XML preserves shape, coords, and mapped-value attributes', () => {
      const reparsed = reparse(
        AreaMapping.fromXML(parseAreaMappingXml(AREA_MAPPING_XML), makeDeclaration()).getXML(),
      );
      const entry = reparsed.querySelector('qti-area-map-entry');
      expect(entry.getAttribute('shape')).toBe('circle');
      expect(entry.getAttribute('coords')).toBe('100,100,50');
      expect(entry.getAttribute('mapped-value')).toBe('1');
    });

    it('re-parsed XML preserves bounds', () => {
      const reparsed = reparse(
        AreaMapping.fromXML(
          parseAreaMappingXml(AREA_MAPPING_WITH_BOUNDS_XML),
          makeDeclaration(),
        ).getXML(),
      );
      expect(reparsed.getAttribute('lower-bound')).toBe('-2');
      expect(reparsed.getAttribute('upper-bound')).toBe('3');
    });
  });
});
