// Disabled because jest-dom matchers (toHaveAttribute/toHaveTextContent) are designed for
// HTML and do not work reliably on strict XML elements generated by serialization.
/* eslint-disable jest-dom/prefer-to-have-attribute, jest-dom/prefer-to-have-text-content */
import { QTIDeclaration } from '../QTIDeclaration.js';
import { CAPABILITY } from '../declarations/index.js';
import { parseXML, reparse, serializeXML } from './testUtils.js';
import {
  DECLARATION_WITH_MAPPING,
  MULTI_SELECT_DECLARATION,
  NO_BASETYPE_DECLARATION,
  OUTCOME_DECLARATION,
  SINGLE_SELECT_DECLARATION,
} from './fixtures/declarations.js';

describe('QTIDeclaration constructor', () => {
  it('stores scalar fields', () => {
    const d = new QTIDeclaration({
      identifier: 'RESPONSE',
      baseType: 'identifier',
      cardinality: 'single',
    });
    expect(d.identifier).toBe('RESPONSE');
    expect(d.baseType).toBe('identifier');
    expect(d.cardinality).toBe('single');
  });

  it('defaults baseType to null and cardinality to single', () => {
    const d = new QTIDeclaration({ identifier: 'SCORE' });
    expect(d.baseType).toBeNull();
    expect(d.cardinality).toBe('single');
  });

  it('throws an error if cardinality is "record"', () => {
    expect(() => {
      new QTIDeclaration({ identifier: 'X', cardinality: 'record' });
    }).toThrow('cardinality="record" is not yet supported');
  });

  it('starts with no capabilities', () => {
    const d = new QTIDeclaration({ identifier: 'X' });
    expect(d.correctResponse).toBeNull();
    expect(d.defaultValue).toBeNull();
    expect(d.mapping).toBeNull();
    expect(d.areaMapping).toBeNull();
  });

  it('defaults tag to qti-response-declaration', () => {
    const d = new QTIDeclaration({ identifier: 'X' });
    expect(d.tag).toBe('qti-response-declaration');
  });
});

describe('QTIDeclaration.registerCapability', () => {
  it('stores and exposes a capability via its getter', () => {
    const d = new QTIDeclaration({ identifier: 'X' });
    const fakeCR = { get: () => ['A'], getXML: () => null };
    d.registerCapability(CAPABILITY.CORRECT_RESPONSE, fakeCR);
    expect(d.correctResponse).toEqual(['A']);
  });
});

describe('QTIDeclaration.fromXML', () => {
  it('reads identifier from XML', () => {
    const d = QTIDeclaration.fromXML(parseXML(SINGLE_SELECT_DECLARATION));
    expect(d.identifier).toBe('RESPONSE');
  });

  it('reads base-type from XML', () => {
    const d = QTIDeclaration.fromXML(parseXML(SINGLE_SELECT_DECLARATION));
    expect(d.baseType).toBe('identifier');
  });

  it('reads cardinality from XML', () => {
    const d = QTIDeclaration.fromXML(parseXML(SINGLE_SELECT_DECLARATION));
    expect(d.cardinality).toBe('single');
  });

  it('stores the original tag name', () => {
    const d = QTIDeclaration.fromXML(parseXML(OUTCOME_DECLARATION));
    expect(d.tag).toBe('qti-outcome-declaration');
  });

  it('registers a correctResponse capability from XML', () => {
    const d = QTIDeclaration.fromXML(parseXML(SINGLE_SELECT_DECLARATION));
    expect(d.correctResponse).toEqual(['ChoiceA']);
  });

  it('registers multiple correct response values', () => {
    const d = QTIDeclaration.fromXML(parseXML(MULTI_SELECT_DECLARATION));
    expect(d.correctResponse).toEqual(['ChoiceA', 'ChoiceC']);
  });

  it('registers a mapping capability when qti-mapping is present', () => {
    const d = QTIDeclaration.fromXML(parseXML(DECLARATION_WITH_MAPPING));
    expect(d.mapping).not.toBeNull();
    expect(d.mapping.entries).toHaveLength(2);
  });

  it('handles null base-type gracefully', () => {
    const d = QTIDeclaration.fromXML(parseXML(NO_BASETYPE_DECLARATION));
    expect(d.baseType).toBeNull();
    expect(d.correctResponse).toEqual(['true']);
  });

  it('ignores unrecognized child elements', () => {
    const xml = `
      <qti-response-declaration identifier="X" base-type="string" cardinality="single">
        <qti-unknown-element/>
      </qti-response-declaration>
    `.trim();
    expect(() => QTIDeclaration.fromXML(parseXML(xml))).not.toThrow();
  });

  it('produces no capabilities for a declaration with no known children', () => {
    const d = QTIDeclaration.fromXML(parseXML(OUTCOME_DECLARATION));
    expect(d.correctResponse).toBeNull();
    expect(d.defaultValue).toBeNull();
    expect(d.mapping).toBeNull();
    expect(d.areaMapping).toBeNull();
  });
});

describe('QTIDeclaration.getXML', () => {
  it('produces an element with the correct tag', () => {
    const d = QTIDeclaration.fromXML(parseXML(SINGLE_SELECT_DECLARATION));
    expect(d.getXML().tagName).toBe('qti-response-declaration');
  });

  it('preserves the outcome-declaration tag on round-trip', () => {
    const d = QTIDeclaration.fromXML(parseXML(OUTCOME_DECLARATION));
    expect(d.getXML().tagName).toBe('qti-outcome-declaration');
  });

  it('preserves identifier on round-trip', () => {
    const d = QTIDeclaration.fromXML(parseXML(SINGLE_SELECT_DECLARATION));
    expect(d.getXML().getAttribute('identifier')).toBe('RESPONSE');
  });

  it('preserves base-type on round-trip', () => {
    const d = QTIDeclaration.fromXML(parseXML(SINGLE_SELECT_DECLARATION));
    expect(d.getXML().getAttribute('base-type')).toBe('identifier');
  });

  it('omits base-type attr when null', () => {
    const d = QTIDeclaration.fromXML(parseXML(NO_BASETYPE_DECLARATION));
    expect(d.getXML().hasAttribute('base-type')).toBe(false);
  });

  it('includes qti-correct-response child on round-trip', () => {
    const d = QTIDeclaration.fromXML(parseXML(SINGLE_SELECT_DECLARATION));
    const xml = serializeXML(d.getXML());
    expect(xml).toContain('qti-correct-response');
    expect(xml).toContain('ChoiceA');
  });

  it('includes qti-mapping child when mapping is present', () => {
    const d = QTIDeclaration.fromXML(parseXML(DECLARATION_WITH_MAPPING));
    const xml = serializeXML(d.getXML());
    expect(xml).toContain('qti-mapping');
    expect(xml).toContain('map-key="ChoiceA"');
  });

  it('full round-trip: fromXML → getXML preserves structure', () => {
    const d = QTIDeclaration.fromXML(parseXML(MULTI_SELECT_DECLARATION));
    const node = d.getXML();
    const values = [...node.querySelectorAll('qti-correct-response qti-value')].map(
      n => n.textContent,
    );
    expect(values).toEqual(['ChoiceA', 'ChoiceC']);
  });
});

describe('QTIDeclaration full XML output (QTI compatibility)', () => {
  it('serializes a single-select declaration to well-formed XML', () => {
    const d = QTIDeclaration.fromXML(parseXML(SINGLE_SELECT_DECLARATION));
    expect(() => reparse(d.getXML())).not.toThrow();
  });

  it('re-parsed XML has qti-response-declaration root tag', () => {
    const reparsed = reparse(QTIDeclaration.fromXML(parseXML(SINGLE_SELECT_DECLARATION)).getXML());
    expect(reparsed.tagName).toBe('qti-response-declaration');
  });

  it('re-parsed XML preserves identifier attribute', () => {
    const reparsed = reparse(QTIDeclaration.fromXML(parseXML(SINGLE_SELECT_DECLARATION)).getXML());
    expect(reparsed.getAttribute('identifier')).toBe('RESPONSE');
  });

  it('re-parsed XML preserves base-type attribute', () => {
    const reparsed = reparse(QTIDeclaration.fromXML(parseXML(SINGLE_SELECT_DECLARATION)).getXML());
    expect(reparsed.getAttribute('base-type')).toBe('identifier');
  });

  it('re-parsed XML preserves cardinality attribute', () => {
    const reparsed = reparse(QTIDeclaration.fromXML(parseXML(MULTI_SELECT_DECLARATION)).getXML());
    expect(reparsed.getAttribute('cardinality')).toBe('multiple');
  });

  it('re-parsed XML contains qti-correct-response child', () => {
    const reparsed = reparse(QTIDeclaration.fromXML(parseXML(SINGLE_SELECT_DECLARATION)).getXML());
    expect(reparsed.querySelector('qti-correct-response')).not.toBeNull();
  });

  it('re-parsed XML correct-response values are intact', () => {
    const reparsed = reparse(QTIDeclaration.fromXML(parseXML(MULTI_SELECT_DECLARATION)).getXML());
    const values = [...reparsed.querySelectorAll('qti-correct-response qti-value')].map(
      n => n.textContent,
    );
    expect(values).toEqual(['ChoiceA', 'ChoiceC']);
  });

  it('re-parsed XML with qti-mapping has correct map entries', () => {
    const reparsed = reparse(QTIDeclaration.fromXML(parseXML(DECLARATION_WITH_MAPPING)).getXML());
    const entries = [...reparsed.querySelectorAll('qti-mapping qti-map-entry')];
    expect(entries).toHaveLength(2);
    expect(entries[0].getAttribute('map-key')).toBe('ChoiceA');
    expect(entries[0].getAttribute('mapped-value')).toBe('1');
  });

  it('omits base-type attr when null on re-parse', () => {
    const reparsed = reparse(QTIDeclaration.fromXML(parseXML(NO_BASETYPE_DECLARATION)).getXML());
    expect(reparsed.hasAttribute('base-type')).toBe(false);
  });

  it('preserves outcome-declaration tag on full re-parse', () => {
    const reparsed = reparse(QTIDeclaration.fromXML(parseXML(OUTCOME_DECLARATION)).getXML());
    expect(reparsed.tagName).toBe('qti-outcome-declaration');
  });

  // Identifier values can contain non-ASCII chars in i18n item banks
  it('handles non-ASCII identifiers in serialized XML (i18n)', () => {
    const d = new QTIDeclaration({
      identifier: 'RÉSPONSE_日本語',
      baseType: 'identifier',
      cardinality: 'single',
    });
    const reparsed = reparse(d.getXML());
    expect(reparsed.getAttribute('identifier')).toBe('RÉSPONSE_日本語');
  });
});

describe('QTIDeclaration.coerceValue', () => {
  describe('null / empty handling', () => {
    it.each([null, undefined, '', 'NULL'])('returns null for %p', raw => {
      expect(QTIDeclaration.coerceValue(raw, 'identifier')).toBeNull();
    });
  });

  describe('boolean', () => {
    it('coerces "true" to true', () => {
      expect(QTIDeclaration.coerceValue('true', 'boolean')).toBe(true);
    });
    it('coerces "false" to false', () => {
      expect(QTIDeclaration.coerceValue('false', 'boolean')).toBe(false);
    });
    it('throws for invalid boolean string', () => {
      expect(() => QTIDeclaration.coerceValue('yes', 'boolean')).toThrow(TypeError);
    });
  });

  describe('integer', () => {
    it('coerces "42" to 42', () => {
      expect(QTIDeclaration.coerceValue('42', 'integer')).toBe(42);
    });
    it('throws for non-numeric string', () => {
      expect(() => QTIDeclaration.coerceValue('abc', 'integer')).toThrow(TypeError);
    });
  });

  describe('float', () => {
    it('coerces "3.14" to 3.14', () => {
      expect(QTIDeclaration.coerceValue('3.14', 'float')).toBeCloseTo(3.14);
    });
    it('throws for non-numeric string', () => {
      expect(() => QTIDeclaration.coerceValue('abc', 'float')).toThrow(TypeError);
    });
  });

  describe('point', () => {
    it('coerces "100 200" to [100, 200]', () => {
      expect(QTIDeclaration.coerceValue('100 200', 'point')).toEqual([100, 200]);
    });
    it('coerces a 2-element array of strings', () => {
      expect(QTIDeclaration.coerceValue(['10', '20'], 'point')).toEqual([10, 20]);
    });
    it('throws for a string with wrong number of parts', () => {
      expect(() => QTIDeclaration.coerceValue('100', 'point')).toThrow(TypeError);
    });
  });

  describe('pair', () => {
    it('coerces "A B" to ["A", "B"]', () => {
      expect(QTIDeclaration.coerceValue('A B', 'pair')).toEqual(['A', 'B']);
    });
    it('coerces a 2-element array', () => {
      expect(QTIDeclaration.coerceValue(['A', 'B'], 'pair')).toEqual(['A', 'B']);
    });
    it('throws for a string with wrong number of parts', () => {
      expect(() => QTIDeclaration.coerceValue('A', 'pair')).toThrow(TypeError);
    });
  });

  describe('directedPair', () => {
    it('coerces "A B" to ["A", "B"]', () => {
      expect(QTIDeclaration.coerceValue('A B', 'directedPair')).toEqual(['A', 'B']);
    });
    it('throws for a string with wrong number of parts', () => {
      expect(() => QTIDeclaration.coerceValue('A', 'directedPair')).toThrow(TypeError);
    });
  });

  describe('duration', () => {
    it('coerces "3600" to 3600', () => {
      expect(QTIDeclaration.coerceValue('3600', 'duration')).toBe(3600);
    });
    it('throws for a negative duration', () => {
      expect(() => QTIDeclaration.coerceValue('-1', 'duration')).toThrow(TypeError);
    });
    it('throws for a non-numeric duration', () => {
      expect(() => QTIDeclaration.coerceValue('abc', 'duration')).toThrow(TypeError);
    });
  });

  describe('identifier / string / uri', () => {
    it('returns the raw string for identifier', () => {
      expect(QTIDeclaration.coerceValue('ChoiceA', 'identifier')).toBe('ChoiceA');
    });
    it('returns the raw string for string', () => {
      expect(QTIDeclaration.coerceValue('hello', 'string')).toBe('hello');
    });
    it('returns the raw string for uri', () => {
      expect(QTIDeclaration.coerceValue('https://example.com', 'uri')).toBe('https://example.com');
    });
  });
});

describe('QTIDeclaration.formatValue', () => {
  it('formats null to empty string', () => {
    expect(QTIDeclaration.formatValue(null)).toBe('');
  });
  it('formats undefined to empty string', () => {
    expect(QTIDeclaration.formatValue(undefined)).toBe('');
  });
  it('formats true to "true"', () => {
    expect(QTIDeclaration.formatValue(true)).toBe('true');
  });
  it('formats false to "false"', () => {
    expect(QTIDeclaration.formatValue(false)).toBe('false');
  });
  it('formats a number to its string representation', () => {
    expect(QTIDeclaration.formatValue(3.14)).toBe('3.14');
  });
  it('formats an array (point/pair) to space-separated string', () => {
    expect(QTIDeclaration.formatValue([100, 200])).toBe('100 200');
    expect(QTIDeclaration.formatValue(['A', 'B'])).toBe('A B');
  });
  it('returns strings unchanged', () => {
    expect(QTIDeclaration.formatValue('ChoiceA')).toBe('ChoiceA');
  });
});

describe('coerceValue → formatValue round-trip', () => {
  it.each([
    ['boolean', 'true', true],
    ['integer', '42', 42],
    ['float', '3.14', 3.14],
    ['point', '100 200', [100, 200]],
    ['pair', 'A B', ['A', 'B']],
    ['directedPair', 'A B', ['A', 'B']],
    ['duration', '3600', 3600],
    ['identifier', 'ChoiceA', 'ChoiceA'],
    ['string', 'hello', 'hello'],
  ])('round-trips %s value', (baseType, raw, coerced) => {
    expect(QTIDeclaration.coerceValue(raw, baseType)).toEqual(coerced);
    expect(QTIDeclaration.formatValue(coerced)).toBe(raw);
  });
});
