// Disabled because jest-dom matchers (toHaveAttribute/toHaveTextContent) are designed for
// HTML and do not work reliably on strict XML elements generated by serialization.
/* eslint-disable jest-dom/prefer-to-have-attribute, jest-dom/prefer-to-have-text-content */
import { buildXmlNode } from '../assembleItem.js';

const serializer = new XMLSerializer();

describe('assembleItem', () => {
  describe('tag and attributes', () => {
    it('creates an element with the given tag name', () => {
      const node = buildXmlNode({ tag: 'qti-response-declaration' });
      expect(node.tagName).toBe('qti-response-declaration');
    });

    it('sets string attributes', () => {
      const node = buildXmlNode({
        tag: 'qti-response-declaration',
        attrs: { identifier: 'RESPONSE', cardinality: 'single', 'base-type': 'identifier' },
      });
      expect(node.getAttribute('identifier')).toBe('RESPONSE');
      expect(node.getAttribute('cardinality')).toBe('single');
      expect(node.getAttribute('base-type')).toBe('identifier');
    });

    it('coerces numeric attribute values to strings', () => {
      const node = buildXmlNode({ tag: 'qti-map-entry', attrs: { 'mapped-value': 1.5 } });
      expect(node.getAttribute('mapped-value')).toBe('1.5');
    });

    it('skips null attribute values', () => {
      const node = buildXmlNode({ tag: 'qti-response-declaration', attrs: { 'base-type': null } });
      expect(node.hasAttribute('base-type')).toBe(false);
    });

    it('skips undefined attribute values', () => {
      const node = buildXmlNode({
        tag: 'qti-response-declaration',
        attrs: { 'base-type': undefined },
      });
      expect(node.hasAttribute('base-type')).toBe(false);
    });

    it('produces an element with no attributes when attrs is omitted', () => {
      const node = buildXmlNode({ tag: 'qti-correct-response' });
      expect(node.attributes.length).toBe(0);
    });
  });

  describe('string children', () => {
    it('appends a text node for a string child', () => {
      const node = buildXmlNode({ tag: 'qti-value', children: ['ChoiceA'] });
      expect(node.textContent).toBe('ChoiceA');
    });

    it('handles multiple string children as separate text nodes', () => {
      const node = buildXmlNode({ tag: 'qti-value', children: ['hello', ' ', 'world'] });
      expect(node.textContent).toBe('hello world');
    });
  });

  describe('element children', () => {
    it('appends child element nodes', () => {
      const child = buildXmlNode({ tag: 'qti-value', children: ['ChoiceA'] });
      const parent = buildXmlNode({ tag: 'qti-correct-response', children: [child] });
      const childEls = parent.getElementsByTagName('qti-value');
      expect(childEls.length).toBe(1);
      expect(childEls[0].textContent).toBe('ChoiceA');
    });

    it('appends multiple element children in order', () => {
      const childA = buildXmlNode({ tag: 'qti-value', children: ['A'] });
      const childB = buildXmlNode({ tag: 'qti-value', children: ['B'] });
      const parent = buildXmlNode({ tag: 'qti-correct-response', children: [childA, childB] });
      const values = [...parent.getElementsByTagName('qti-value')].map(n => n.textContent);
      expect(values).toEqual(['A', 'B']);
    });
  });

  describe('mixed children', () => {
    it('handles a mix of element and string children', () => {
      const child = buildXmlNode({ tag: 'qti-value', children: ['X'] });
      const parent = buildXmlNode({ tag: 'qti-correct-response', children: ['prefix', child] });
      // First child is a text node
      expect(parent.childNodes[0].nodeType).toBe(Node.TEXT_NODE);
      expect(parent.childNodes[0].textContent).toBe('prefix');
      // Second child is the element
      expect(parent.childNodes[1].tagName).toBe('qti-value');
    });
  });

  describe('serialization', () => {
    it('round-trips through XMLSerializer', () => {
      const node = buildXmlNode({
        tag: 'qti-response-declaration',
        attrs: { identifier: 'RESPONSE', cardinality: 'single', 'base-type': 'identifier' },
        children: [
          buildXmlNode({
            tag: 'qti-correct-response',
            children: [buildXmlNode({ tag: 'qti-value', children: ['ChoiceA'] })],
          }),
        ],
      });

      const xml = serializer.serializeToString(node);
      expect(xml).toContain('qti-response-declaration');
      expect(xml).toContain('identifier="RESPONSE"');
      expect(xml).toContain('qti-correct-response');
      expect(xml).toContain('ChoiceA');
    });
  });
});
