// Disabled because jest-dom matchers (toHaveAttribute/toHaveTextContent) are designed for
// HTML and do not work reliably on strict XML elements generated by serialization.
/* eslint-disable jest-dom/prefer-to-have-attribute, jest-dom/prefer-to-have-text-content */
import { buildXmlNode, assembleItemXml } from '../assembleItem.js';
import { parseItem } from '../parseItem.js';
import { parseXML } from '../xml.js';
import { MULTI_TEXT_ENTRY_ITEM_DOCUMENT } from '../../utils/testingFixtures';

const serializer = new XMLSerializer();

describe('assembleItem', () => {
  describe('tag and attributes', () => {
    it('creates an element with the given tag name', () => {
      const node = buildXmlNode({ tag: 'qti-response-declaration' });
      expect(node.tagName).toBe('qti-response-declaration');
    });

    it('sets string attributes', () => {
      const node = buildXmlNode({
        tag: 'qti-response-declaration',
        attrs: { identifier: 'RESPONSE', cardinality: 'single', 'base-type': 'identifier' },
      });
      expect(node.getAttribute('identifier')).toBe('RESPONSE');
      expect(node.getAttribute('cardinality')).toBe('single');
      expect(node.getAttribute('base-type')).toBe('identifier');
    });

    it('coerces numeric attribute values to strings', () => {
      const node = buildXmlNode({ tag: 'qti-map-entry', attrs: { 'mapped-value': 1.5 } });
      expect(node.getAttribute('mapped-value')).toBe('1.5');
    });

    it('skips null attribute values', () => {
      const node = buildXmlNode({ tag: 'qti-response-declaration', attrs: { 'base-type': null } });
      expect(node.hasAttribute('base-type')).toBe(false);
    });

    it('skips undefined attribute values', () => {
      const node = buildXmlNode({
        tag: 'qti-response-declaration',
        attrs: { 'base-type': undefined },
      });
      expect(node.hasAttribute('base-type')).toBe(false);
    });

    it('produces an element with no attributes when attrs is omitted', () => {
      const node = buildXmlNode({ tag: 'qti-correct-response' });
      expect(node.attributes.length).toBe(0);
    });
  });

  describe('string children', () => {
    it('appends a text node for a string child', () => {
      const node = buildXmlNode({ tag: 'qti-value', children: ['ChoiceA'] });
      expect(node.textContent).toBe('ChoiceA');
    });

    it('handles multiple string children as separate text nodes', () => {
      const node = buildXmlNode({ tag: 'qti-value', children: ['hello', ' ', 'world'] });
      expect(node.textContent).toBe('hello world');
    });
  });

  describe('element children', () => {
    it('appends child element nodes', () => {
      const child = buildXmlNode({ tag: 'qti-value', children: ['ChoiceA'] });
      const parent = buildXmlNode({ tag: 'qti-correct-response', children: [child] });
      const childEls = parent.getElementsByTagName('qti-value');
      expect(childEls.length).toBe(1);
      expect(childEls[0].textContent).toBe('ChoiceA');
    });

    it('appends multiple element children in order', () => {
      const childA = buildXmlNode({ tag: 'qti-value', children: ['A'] });
      const childB = buildXmlNode({ tag: 'qti-value', children: ['B'] });
      const parent = buildXmlNode({ tag: 'qti-correct-response', children: [childA, childB] });
      const values = [...parent.getElementsByTagName('qti-value')].map(n => n.textContent);
      expect(values).toEqual(['A', 'B']);
    });

    it('imports element children from another XML document', () => {
      const child = new DOMParser().parseFromString(
        '<qti-value>ChoiceA</qti-value>',
        'text/xml',
      ).documentElement;
      const parent = buildXmlNode({ tag: 'qti-correct-response', children: [child] });
      expect(parent.getElementsByTagName('qti-value')[0].textContent).toBe('ChoiceA');
    });
  });

  describe('mixed children', () => {
    it('handles a mix of element and string children', () => {
      const child = buildXmlNode({ tag: 'qti-value', children: ['X'] });
      const parent = buildXmlNode({ tag: 'qti-correct-response', children: ['prefix', child] });
      // First child is a text node
      expect(parent.childNodes[0].nodeType).toBe(Node.TEXT_NODE);
      expect(parent.childNodes[0].textContent).toBe('prefix');
      // Second child is the element
      expect(parent.childNodes[1].tagName).toBe('qti-value');
    });
  });

  describe('serialization', () => {
    it('round-trips through XMLSerializer', () => {
      const node = buildXmlNode({
        tag: 'qti-response-declaration',
        attrs: { identifier: 'RESPONSE', cardinality: 'single', 'base-type': 'identifier' },
        children: [
          buildXmlNode({
            tag: 'qti-correct-response',
            children: [buildXmlNode({ tag: 'qti-value', children: ['ChoiceA'] })],
          }),
        ],
      });

      const xml = serializer.serializeToString(node);
      expect(xml).toContain('qti-response-declaration');
      expect(xml).toContain('identifier="RESPONSE"');
      expect(xml).toContain('qti-correct-response');
      expect(xml).toContain('ChoiceA');
    });
  });

  describe('innerHTML option', () => {
    it('appends plain text via innerHTML', () => {
      const node = buildXmlNode({ tag: 'qti-simple-choice', innerHTML: 'Mercury' });
      expect(node.textContent).toBe('Mercury');
    });

    it('appends rich markup via innerHTML', () => {
      const node = buildXmlNode({
        tag: 'qti-simple-choice',
        innerHTML: '<p>Option <strong>A</strong></p>',
      });
      expect(node.querySelector('strong').textContent).toBe('A');
    });

    it('handles empty innerHTML without throwing', () => {
      const node = buildXmlNode({ tag: 'qti-simple-choice', innerHTML: '' });
      expect(node.childNodes.length).toBe(0);
    });

    it('throws when both children and innerHTML are provided', () => {
      expect(() =>
        buildXmlNode({ tag: 'qti-simple-choice', children: ['x'], innerHTML: '<p>y</p>' }),
      ).toThrow('mutually exclusive');
    });

    it('leaves no xhtml namespace on the markup it appends', () => {
      // The QTI schema expects inline content in the namespace the item root declares, so
      // an explicit xmlns from the HTML parser makes the whole item invalid on the server.
      const node = buildXmlNode({
        tag: 'qti-simple-choice',
        innerHTML: '<p>Lima</p>',
      });
      expect(new XMLSerializer().serializeToString(node)).toBe(
        '<qti-simple-choice><p>Lima</p></qti-simple-choice>',
      );
    });

    it('drops an xhtml namespace already carried by stored content', () => {
      const node = buildXmlNode({
        tag: 'qti-simple-choice',
        innerHTML: '<p xmlns="http://www.w3.org/1999/xhtml">Lima</p>',
      });
      expect(new XMLSerializer().serializeToString(node)).toBe(
        '<qti-simple-choice><p>Lima</p></qti-simple-choice>',
      );
    });

    it('keeps a foreign namespace, which QTI expects declared', () => {
      const node = buildXmlNode({
        tag: 'qti-prompt',
        innerHTML: '<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>x</mi></math>',
      });
      expect(new XMLSerializer().serializeToString(node)).toContain(
        '<math xmlns="http://www.w3.org/1998/Math/MathML">',
      );
    });
  });

  describe('innerHTML — HTML5 void elements (TipTap regression)', () => {
    it('handles a bare <br> without producing a parseerror in the XML output', () => {
      const node = buildXmlNode({
        tag: 'qti-prompt',
        innerHTML: '<p>Line one</p><br><p>Line two</p>',
      });
      // Serialized output must be valid XML
      const xml = serializer.serializeToString(node);
      const doc = new DOMParser().parseFromString(xml, 'text/xml');
      expect(doc.querySelector('parsererror')).toBeNull();
    });

    it('preserves text content when innerHTML contains a <br>', () => {
      const node = buildXmlNode({
        tag: 'qti-prompt',
        innerHTML: '<p>First</p><br><p>Second</p>',
      });
      expect(node.textContent).toContain('First');
      expect(node.textContent).toContain('Second');
    });

    it('handles an unclosed <img> without producing a parseerror', () => {
      const node = buildXmlNode({
        tag: 'qti-simple-choice',
        innerHTML: '<img src="cat.png" alt="cat"><span>A cat</span>',
      });
      const xml = serializer.serializeToString(node);
      const doc = new DOMParser().parseFromString(xml, 'text/xml');
      expect(doc.querySelector('parsererror')).toBeNull();
      expect(node.textContent).toContain('A cat');
    });

    it('self-closes void elements in the serialized XML output', () => {
      const node = buildXmlNode({ tag: 'qti-prompt', innerHTML: 'Hello<br>World' });
      const xml = serializer.serializeToString(node);
      // <br> must be self-closed in the output (br/ or br with no children)
      expect(xml).toMatch(/<br[\s/]/);
      // And the result must still parse without error
      expect(
        new DOMParser().parseFromString(xml, 'text/xml').querySelector('parsererror'),
      ).toBeNull();
    });

    it('preserves well-formed HTML markup correctly', () => {
      const node = buildXmlNode({
        tag: 'qti-simple-choice',
        innerHTML: '<p>Option <strong>A</strong></p>',
      });
      expect(node.querySelector('strong').textContent).toBe('A');
    });
  });
});

describe('assembleItemXml', () => {
  const BASE = {
    bodyXml: '<qti-choice-interaction response-identifier="RESPONSE" max-choices="1"/>',
    responseDeclarations: [],
  };

  const identifiersOf = (xml, selector) =>
    [...parseXML(xml).querySelectorAll(selector)].map(el => el.getAttribute('identifier'));

  it('escapes & in the title so the output is well-formed XML', () => {
    const xml = assembleItemXml({
      ...BASE,
      identifier: 'item-1',
      title: 'Math & Science',
      language: 'en',
    });
    expect(xml).toContain('title="Math &amp; Science"');
    expect(
      new DOMParser().parseFromString(xml, 'text/xml').querySelector('parsererror'),
    ).toBeNull();
  });

  it('escapes " in the title so the attribute value is not terminated early', () => {
    const xml = assembleItemXml({
      ...BASE,
      identifier: 'item-1',
      title: 'The "Quiz"',
      language: 'en',
    });
    expect(xml).toContain('title="The &quot;Quiz&quot;"');
    expect(
      new DOMParser().parseFromString(xml, 'text/xml').querySelector('parsererror'),
    ).toBeNull();
  });

  it('escapes < in the identifier so the tag is not corrupted', () => {
    const xml = assembleItemXml({ ...BASE, identifier: 'a<b', title: 'T', language: 'en' });
    expect(xml).toContain('identifier="a&lt;b"');
    expect(
      new DOMParser().parseFromString(xml, 'text/xml').querySelector('parsererror'),
    ).toBeNull();
  });

  it('produces a round-trippable document when all fields are clean', () => {
    const xml = assembleItemXml({
      ...BASE,
      identifier: 'item-clean',
      title: 'Plain Title',
      language: 'en',
    });
    const doc = new DOMParser().parseFromString(xml, 'text/xml');
    expect(doc.querySelector('parsererror')).toBeNull();
    expect(doc.querySelector('qti-assessment-item').getAttribute('title')).toBe('Plain Title');
  });

  describe('namespaces', () => {
    const MATHML_NS = 'http://www.w3.org/1998/Math/MathML';
    const QTI_NS = 'http://www.imsglobal.org/xsd/imsqtiasi_v3p0';

    // buildXmlNode gets this right on its own, but the body is handed here as a string
    // and parsed again, so the declaration has to survive that too. A <math> that ends
    // up inheriting the QTI namespace makes the server reject the whole item.
    it('keeps a foreign namespace declared inside the body', () => {
      const prompt = buildXmlNode({
        tag: 'qti-prompt',
        innerHTML: `<p>What is <math xmlns="${MATHML_NS}"><mi>x</mi></math>?</p>`,
      });
      const interaction = buildXmlNode({
        tag: 'qti-choice-interaction',
        attrs: { 'response-identifier': 'RESPONSE' },
        children: [prompt],
      });

      const xml = assembleItemXml({
        identifier: 'item-math',
        title: 'T',
        language: 'en',
        bodyXml: serializer.serializeToString(interaction),
        responseDeclarations: [],
      });

      expect(
        new DOMParser().parseFromString(xml, 'text/xml').querySelector('math').namespaceURI,
      ).toBe(MATHML_NS);
    });

    // An interaction the author did not touch is handed back exactly as parseItem read
    // it, still carrying the item's own declaration. Re-declaring the same namespace is
    // redundant but valid, and it must not cost the foreign one nested inside.
    it('assembles a body whose root already declares the QTI namespace', () => {
      const xml = assembleItemXml({
        identifier: 'item-math',
        title: 'T',
        language: 'en',
        bodyXml:
          `<qti-choice-interaction xmlns="${QTI_NS}" response-identifier="RESPONSE">` +
          `<qti-prompt><p>What is <math xmlns="${MATHML_NS}"><mi>x</mi></math>?</p></qti-prompt>` +
          `</qti-choice-interaction>`,
        responseDeclarations: [],
      });

      const doc = new DOMParser().parseFromString(xml, 'text/xml');
      expect(doc.querySelector('parsererror')).toBeNull();
      expect(doc.querySelector('qti-choice-interaction').namespaceURI).toBe(QTI_NS);
      expect(doc.querySelector('math').namespaceURI).toBe(MATHML_NS);
    });

    it('preserves MathML through a parseItem round trip', () => {
      const original =
        '<?xml version="1.0" encoding="UTF-8"?>\n' +
        `<qti-assessment-item xmlns="${QTI_NS}" identifier="item-math" title="T" adaptive="false" time-dependent="false" xml:lang="en">` +
        '<qti-item-body><qti-choice-interaction response-identifier="RESPONSE">' +
        `<qti-prompt><p>What is <math xmlns="${MATHML_NS}"><mi>x</mi></math>?</p></qti-prompt>` +
        '</qti-choice-interaction></qti-item-body></qti-assessment-item>';

      const item = parseItem(original);
      const xml = assembleItemXml({
        identifier: item.identifier,
        title: item.title,
        language: item.language,
        bodyXml: item.interactions[0].bodyXml,
        responseDeclarations: item.interactions[0].responseDeclarations,
      });

      expect(
        new DOMParser().parseFromString(xml, 'text/xml').querySelector('math').namespaceURI,
      ).toBe(MATHML_NS);
    });
  });

  describe('response processing', () => {
    const INLINE_CHOICE_BODY =
      '<qti-item-body><p>The Earth ' +
      '<qti-inline-choice-interaction response-identifier="response_xq7tbn2c" shuffle="true">' +
      '<qti-inline-choice identifier="choice_a1b2c3d4">revolves</qti-inline-choice>' +
      '<qti-inline-choice identifier="choice_e5f6g7h8">stays</qti-inline-choice>' +
      '</qti-inline-choice-interaction> around the Sun, and the ' +
      '<qti-inline-choice-interaction response-identifier="response_pw4rzk8d" shuffle="true">' +
      '<qti-inline-choice identifier="choice_s0u0n0aa">Sun</qti-inline-choice>' +
      '<qti-inline-choice identifier="choice_m0o0n0aa">Moon</qti-inline-choice>' +
      '</qti-inline-choice-interaction> orbits the Earth.</p></qti-item-body>';

    const declaration = (identifier, correct) =>
      `<qti-response-declaration identifier="${identifier}" cardinality="single" base-type="identifier">` +
      (correct
        ? `<qti-correct-response><qti-value>${correct}</qti-value></qti-correct-response>`
        : '') +
      '</qti-response-declaration>';

    const rule = identifier =>
      '<qti-response-condition><qti-response-if>' +
      `<qti-match><qti-variable identifier="${identifier}"/><qti-correct identifier="${identifier}"/></qti-match>` +
      '<qti-set-outcome-value identifier="RAW_SCORE"><qti-sum><qti-variable identifier="RAW_SCORE"/>' +
      '<qti-base-value base-type="float">1.0</qti-base-value></qti-sum></qti-set-outcome-value>' +
      '</qti-response-if></qti-response-condition>';

    const EXPECTED_PROCESSING =
      '<qti-response-processing>' +
      '<qti-set-outcome-value identifier="RAW_SCORE"><qti-base-value base-type="float">0.0</qti-base-value></qti-set-outcome-value>' +
      rule('response_xq7tbn2c') +
      rule('response_pw4rzk8d') +
      '<qti-set-outcome-value identifier="SCORE"><qti-divide><qti-variable identifier="RAW_SCORE"/>' +
      '<qti-base-value base-type="float">2.0</qti-base-value></qti-divide></qti-set-outcome-value>' +
      '</qti-response-processing>';

    const assembleWith = responseDeclarations =>
      assembleItemXml({
        identifier: 'item_k2lm9qaz',
        title: 'Question',
        language: '',
        bodyXml: INLINE_CHOICE_BODY,
        responseDeclarations,
      });

    afterEach(() => jest.restoreAllMocks());

    it('scores a single response declaration with the match_correct template', () => {
      const xml = assembleWith([declaration('RESPONSE', 'choice_a1b2c3d4')]);
      const processing = parseXML(xml).querySelector('qti-response-processing');
      expect(processing.getAttribute('template')).toContain('rptemplates/match_correct');
      expect(processing.children).toHaveLength(0);
      expect(identifiersOf(xml, 'qti-outcome-declaration')).toEqual(['SCORE']);
    });

    it('averages the scoring rules of several scorable response declarations', () => {
      const xml = assembleWith([
        declaration('response_xq7tbn2c', 'choice_a1b2c3d4'),
        declaration('response_pw4rzk8d', 'choice_m0o0n0aa'),
      ]);
      expect(identifiersOf(xml, 'qti-outcome-declaration')).toEqual(['SCORE', 'RAW_SCORE']);
      expect(xml).toContain(EXPECTED_PROCESSING);
    });

    it('writes no processing and warns when a response declaration cannot be scored', () => {
      const warn = jest.spyOn(console, 'warn').mockImplementation(() => {});
      const xml = assembleWith([
        declaration('response_xq7tbn2c', 'choice_a1b2c3d4'),
        declaration('response_pw4rzk8d'),
      ]);
      expect(parseXML(xml).querySelector('qti-response-processing')).toBeNull();
      expect(identifiersOf(xml, 'qti-outcome-declaration')).toEqual(['SCORE']);
      expect(warn).toHaveBeenCalledTimes(1);
      expect(warn.mock.calls[0][0]).toContain('response_pw4rzk8d');
      expect(warn.mock.calls[0][0]).not.toContain('response_xq7tbn2c');
    });
  });

  describe('an item with several inline interactions', () => {
    // A hint edit reassembles the item from its first block.
    const reassemble = xml => {
      const item = parseItem(xml);
      return assembleItemXml({
        identifier: item.identifier,
        title: item.title,
        language: item.language,
        bodyXml: item.interactions[0].bodyXml,
        responseDeclarations: item.interactions[0].responseDeclarations,
        hints: [{ id: 'h', content: '<p>Look up</p>' }],
      });
    };

    it('keeps every declaration, in body order, and scores them all', () => {
      const xml = reassemble(MULTI_TEXT_ENTRY_ITEM_DOCUMENT);
      expect(identifiersOf(xml, 'qti-response-declaration')).toEqual([
        'response_xq7tbn2c',
        'response_pw4rzk8d',
      ]);
      expect(identifiersOf(xml, 'qti-outcome-declaration')).toEqual(['SCORE', 'RAW_SCORE']);
    });

    it('does not duplicate generated processing when saved again', () => {
      const xml = reassemble(reassemble(MULTI_TEXT_ENTRY_ITEM_DOCUMENT));
      expect(identifiersOf(xml, 'qti-outcome-declaration')).toEqual(['SCORE', 'RAW_SCORE']);
      expect(parseXML(xml).querySelectorAll('qti-response-processing')).toHaveLength(1);
    });
  });
});
