// Disabled because jest-dom matchers (toHaveAttribute/toHaveTextContent) are designed for
// HTML and do not work reliably on strict XML elements generated by serialization.
/* eslint-disable jest-dom/prefer-to-have-attribute, jest-dom/prefer-to-have-text-content */
import { buildXmlNode, parseXML, getPromptHTML, serializeAsHtml } from '../xml';
import { VALID_CHOICE_ITEM_DOCUMENT } from '../../utils/testingFixtures';

const serializer = new XMLSerializer();

// parseXML
describe('parseXML', () => {
  it('parses valid XML into a Document', () => {
    const doc = parseXML(VALID_CHOICE_ITEM_DOCUMENT);
    expect(doc).toBeInstanceOf(Document);
    expect(doc.querySelector('qti-assessment-item')).not.toBeNull();
  });

  it('throws for malformed XML', () => {
    expect(() => parseXML('<unclosed')).toThrow(/QTI XML parse error/i);
  });

  it('throws for XML with a parsererror node', () => {
    // An extra closing tag causes a parsererror in jsdom
    expect(() => parseXML('<root></root></extra>')).toThrow(/QTI XML parse error/i);
  });

  it('parses valid XML when text/xml is passed explicitly', () => {
    const doc = parseXML(VALID_CHOICE_ITEM_DOCUMENT, 'text/xml');
    expect(doc.querySelector('qti-assessment-item')).not.toBeNull();
  });

  it('parses HTML leniently into a Document when text/html is passed', () => {
    const doc = parseXML('<b>bold</b>', 'text/html');
    expect(doc).toBeInstanceOf(Document);
    // doc.body is a DOMParser-realm node, not a testing-library node, so
    // toHaveTextContent rejects it; assert on textContent directly.
    // eslint-disable-next-line jest-dom/prefer-to-have-text-content
    expect(doc.body.textContent).toBe('bold');
  });

  it('does not throw for malformed HTML', () => {
    expect(() => parseXML('<unclosed', 'text/html')).not.toThrow();
  });

  it('does not treat a literal parsererror element in HTML as a failure', () => {
    expect(() => parseXML('<parsererror>x</parsererror>', 'text/html')).not.toThrow();
  });

  it('leaves the namespace declared on the document element in place', () => {
    const doc = parseXML(
      '<qti-assessment-item xmlns="http://www.imsglobal.org/xsd/imsqtiasi_v3p0"/>',
    );
    expect(doc.documentElement.namespaceURI).toBe('http://www.imsglobal.org/xsd/imsqtiasi_v3p0');
  });

  it('leaves a foreign namespace declared on a nested element in place', () => {
    // MathML has to keep its own namespace: without it, serializing the subtree back
    // into a QTI-namespaced item makes <math> inherit the QTI namespace, which the
    // schema rejects.
    const doc = parseXML(
      '<qti-prompt><p>x <math xmlns="http://www.w3.org/1998/Math/MathML"><mi>x</mi></math></p></qti-prompt>',
    );
    expect(doc.querySelector('math').namespaceURI).toBe('http://www.w3.org/1998/Math/MathML');
  });

  it('finds an element by local name regardless of the namespace it is in', () => {
    // Which is why nothing needs the declarations removed to look elements up.
    const doc = parseXML(
      '<qti-assessment-item xmlns="http://www.imsglobal.org/xsd/imsqtiasi_v3p0"><qti-item-body/></qti-assessment-item>',
    );
    expect(doc.querySelector('qti-item-body')).not.toBeNull();
  });
});

describe('getPromptHTML', () => {
  it('returns the prompt markup of an interaction', () => {
    const el = parseXML(
      '<qti-choice-interaction><qti-prompt>Pick <strong>one</strong></qti-prompt></qti-choice-interaction>',
    ).documentElement;

    expect(getPromptHTML(el)).toBe('Pick <strong>one</strong>');
  });

  it('returns an empty string when the interaction has no prompt', () => {
    const el = parseXML('<qti-choice-interaction />').documentElement;

    expect(getPromptHTML(el)).toBe('');
  });
});

describe('buildXmlNode', () => {
  describe('tag and attributes', () => {
    it('creates an element with the given tag name', () => {
      const node = buildXmlNode({ tag: 'qti-response-declaration' });
      expect(node.tagName).toBe('qti-response-declaration');
    });

    it('sets string attributes', () => {
      const node = buildXmlNode({
        tag: 'qti-response-declaration',
        attrs: { identifier: 'RESPONSE', cardinality: 'single', 'base-type': 'identifier' },
      });
      expect(node.getAttribute('identifier')).toBe('RESPONSE');
      expect(node.getAttribute('cardinality')).toBe('single');
      expect(node.getAttribute('base-type')).toBe('identifier');
    });

    it('coerces numeric attribute values to strings', () => {
      const node = buildXmlNode({ tag: 'qti-map-entry', attrs: { 'mapped-value': 1.5 } });
      expect(node.getAttribute('mapped-value')).toBe('1.5');
    });

    it('skips null attribute values', () => {
      const node = buildXmlNode({ tag: 'qti-response-declaration', attrs: { 'base-type': null } });
      expect(node.hasAttribute('base-type')).toBe(false);
    });

    it('skips undefined attribute values', () => {
      const node = buildXmlNode({
        tag: 'qti-response-declaration',
        attrs: { 'base-type': undefined },
      });
      expect(node.hasAttribute('base-type')).toBe(false);
    });

    it('produces an element with no attributes when attrs is omitted', () => {
      const node = buildXmlNode({ tag: 'qti-correct-response' });
      expect(node.attributes.length).toBe(0);
    });
  });

  describe('string children', () => {
    it('appends a text node for a string child', () => {
      const node = buildXmlNode({ tag: 'qti-value', children: ['ChoiceA'] });
      expect(node.textContent).toBe('ChoiceA');
    });

    it('handles multiple string children as separate text nodes', () => {
      const node = buildXmlNode({ tag: 'qti-value', children: ['hello', ' ', 'world'] });
      expect(node.textContent).toBe('hello world');
    });
  });

  describe('element children', () => {
    it('appends child element nodes', () => {
      const child = buildXmlNode({ tag: 'qti-value', children: ['ChoiceA'] });
      const parent = buildXmlNode({ tag: 'qti-correct-response', children: [child] });
      const childEls = parent.getElementsByTagName('qti-value');
      expect(childEls.length).toBe(1);
      expect(childEls[0].textContent).toBe('ChoiceA');
    });

    it('appends multiple element children in order', () => {
      const childA = buildXmlNode({ tag: 'qti-value', children: ['A'] });
      const childB = buildXmlNode({ tag: 'qti-value', children: ['B'] });
      const parent = buildXmlNode({ tag: 'qti-correct-response', children: [childA, childB] });
      const values = [...parent.getElementsByTagName('qti-value')].map(n => n.textContent);
      expect(values).toEqual(['A', 'B']);
    });

    it('imports element children from another XML document', () => {
      const child = new DOMParser().parseFromString(
        '<qti-value>ChoiceA</qti-value>',
        'text/xml',
      ).documentElement;
      const parent = buildXmlNode({ tag: 'qti-correct-response', children: [child] });
      expect(parent.getElementsByTagName('qti-value')[0].textContent).toBe('ChoiceA');
    });
  });

  describe('mixed children', () => {
    it('handles a mix of element and string children', () => {
      const child = buildXmlNode({ tag: 'qti-value', children: ['X'] });
      const parent = buildXmlNode({ tag: 'qti-correct-response', children: ['prefix', child] });
      // First child is a text node
      expect(parent.childNodes[0].nodeType).toBe(Node.TEXT_NODE);
      expect(parent.childNodes[0].textContent).toBe('prefix');
      // Second child is the element
      expect(parent.childNodes[1].tagName).toBe('qti-value');
    });
  });

  describe('serialization', () => {
    it('round-trips through XMLSerializer', () => {
      const node = buildXmlNode({
        tag: 'qti-response-declaration',
        attrs: { identifier: 'RESPONSE', cardinality: 'single', 'base-type': 'identifier' },
        children: [
          buildXmlNode({
            tag: 'qti-correct-response',
            children: [buildXmlNode({ tag: 'qti-value', children: ['ChoiceA'] })],
          }),
        ],
      });

      const xml = serializer.serializeToString(node);
      expect(xml).toContain('qti-response-declaration');
      expect(xml).toContain('identifier="RESPONSE"');
      expect(xml).toContain('qti-correct-response');
      expect(xml).toContain('ChoiceA');
    });
  });

  describe('innerHTML option', () => {
    it('appends plain text via innerHTML', () => {
      const node = buildXmlNode({ tag: 'qti-simple-choice', innerHTML: 'Mercury' });
      expect(node.textContent).toBe('Mercury');
    });

    it('appends rich markup via innerHTML', () => {
      const node = buildXmlNode({
        tag: 'qti-simple-choice',
        innerHTML: '<p>Option <strong>A</strong></p>',
      });
      expect(node.querySelector('strong').textContent).toBe('A');
    });

    it('handles empty innerHTML without throwing', () => {
      const node = buildXmlNode({ tag: 'qti-simple-choice', innerHTML: '' });
      expect(node.childNodes.length).toBe(0);
    });

    it('throws when both children and innerHTML are provided', () => {
      expect(() =>
        buildXmlNode({ tag: 'qti-simple-choice', children: ['x'], innerHTML: '<p>y</p>' }),
      ).toThrow('mutually exclusive');
    });

    it('leaves no xhtml namespace on the markup it appends', () => {
      // The QTI schema expects inline content in the namespace the item root declares, so
      // an explicit xmlns from the HTML parser makes the whole item invalid on the server.
      const node = buildXmlNode({
        tag: 'qti-simple-choice',
        innerHTML: '<p>Lima</p>',
      });
      expect(new XMLSerializer().serializeToString(node)).toBe(
        '<qti-simple-choice><p>Lima</p></qti-simple-choice>',
      );
    });

    it('drops an xhtml namespace already carried by stored content', () => {
      const node = buildXmlNode({
        tag: 'qti-simple-choice',
        innerHTML: '<p xmlns="http://www.w3.org/1999/xhtml">Lima</p>',
      });
      expect(new XMLSerializer().serializeToString(node)).toBe(
        '<qti-simple-choice><p>Lima</p></qti-simple-choice>',
      );
    });

    it('keeps a foreign namespace, which QTI expects declared', () => {
      const node = buildXmlNode({
        tag: 'qti-prompt',
        innerHTML: '<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>x</mi></math>',
      });
      expect(new XMLSerializer().serializeToString(node)).toContain(
        '<math xmlns="http://www.w3.org/1998/Math/MathML">',
      );
    });
  });

  describe('innerHTML — HTML5 void elements (TipTap regression)', () => {
    it('handles a bare <br> without producing a parseerror in the XML output', () => {
      const node = buildXmlNode({
        tag: 'qti-prompt',
        innerHTML: '<p>Line one</p><br><p>Line two</p>',
      });
      // Serialized output must be valid XML
      const xml = serializer.serializeToString(node);
      const doc = new DOMParser().parseFromString(xml, 'text/xml');
      expect(doc.querySelector('parsererror')).toBeNull();
    });

    it('preserves text content when innerHTML contains a <br>', () => {
      const node = buildXmlNode({
        tag: 'qti-prompt',
        innerHTML: '<p>First</p><br><p>Second</p>',
      });
      expect(node.textContent).toContain('First');
      expect(node.textContent).toContain('Second');
    });

    it('handles an unclosed <img> without producing a parseerror', () => {
      const node = buildXmlNode({
        tag: 'qti-simple-choice',
        innerHTML: '<img src="cat.png" alt="cat"><span>A cat</span>',
      });
      const xml = serializer.serializeToString(node);
      const doc = new DOMParser().parseFromString(xml, 'text/xml');
      expect(doc.querySelector('parsererror')).toBeNull();
      expect(node.textContent).toContain('A cat');
    });

    it('self-closes void elements in the serialized XML output', () => {
      const node = buildXmlNode({ tag: 'qti-prompt', innerHTML: 'Hello<br>World' });
      const xml = serializer.serializeToString(node);
      // <br> must be self-closed in the output (br/ or br with no children)
      expect(xml).toMatch(/<br[\s/]/);
      // And the result must still parse without error
      expect(
        new DOMParser().parseFromString(xml, 'text/xml').querySelector('parsererror'),
      ).toBeNull();
    });

    it('preserves well-formed HTML markup correctly', () => {
      const node = buildXmlNode({
        tag: 'qti-simple-choice',
        innerHTML: '<p>Option <strong>A</strong></p>',
      });
      expect(node.querySelector('strong').textContent).toBe('A');
    });
  });
});

describe('serializeAsHtml', () => {
  const QTI_NS = 'http://www.imsglobal.org/xsd/imsqtiasi_v3p0';
  const MATHML_NS = 'http://www.w3.org/1998/Math/MathML';

  function children(xml) {
    return [...parseXML(xml).documentElement.childNodes];
  }

  it('writes an end tag on an empty element, so its siblings stay siblings when re-parsed', () => {
    const html = serializeAsHtml(children('<root><x a="1"/><x a="2">B</x></root>'));
    expect(html).toBe('<x a="1"></x><x a="2">B</x>');
    expect(parseXML(html, 'text/html').querySelectorAll('body > x')).toHaveLength(2);
  });

  it('drops the xmlns of elements in the given namespace', () => {
    const html = serializeAsHtml(children(`<root xmlns="${QTI_NS}"><p>Text</p></root>`), QTI_NS);
    expect(html).toBe('<p>Text</p>');
  });

  it('keeps a foreign subtree in its own namespace', () => {
    const nodes = children(
      `<root xmlns="${QTI_NS}"><math xmlns="${MATHML_NS}"><mi>x</mi></math></root>`,
    );
    const math = parseXML(serializeAsHtml(nodes, QTI_NS), 'text/html').querySelector('math');
    expect(math.namespaceURI).toBe(MATHML_NS);
  });

  it('skips comments', () => {
    expect(serializeAsHtml(children('<root><!-- note --><p>a</p></root>'))).toBe('<p>a</p>');
  });
});
