# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-28 00:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_auto_20180327_1414"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentnode",
            name="coach_content",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
