# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 17:09
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20180910_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnode',
            name='kind',
            field=models.CharField(blank=True, choices=[('topic', b'Topic'), ('video', b'Video'), ('audio', b'Audio'), ('exercise', b'Exercise'), ('document', b'Document'), ('html5', b'HTML5 App'), ('slideshow', b'Slideshow')], max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='preset',
            field=models.CharField(blank=True, choices=[('high_res_video', b'High Resolution'), ('low_res_video', b'Low Resolution'), ('video_thumbnail', b'Thumbnail'), ('video_subtitle', b'Subtitle'), ('video_dependency', b'Video (dependency)'), ('audio', b'Audio'), ('audio_thumbnail', b'Thumbnail'), ('document', b'Document'), ('epub', b'ePub Document'), ('document_thumbnail', b'Thumbnail'), ('exercise', b'Exercise'), ('exercise_thumbnail', b'Thumbnail'), ('exercise_image', b'Exercise Image'), ('exercise_graphie', b'Exercise Graphie'), ('channel_thumbnail', b'Channel Thumbnail'), ('topic_thumbnail', b'Thumbnail'), ('html5_zip', b'HTML5 Zip'), ('html5_dependency', b'HTML5 Dependency (Zip format)'), ('html5_thumbnail', b'HTML5 Thumbnail'), ('slideshow_image', b'Slideshow Image'), ('slideshow_thumbnail', b'Slideshow Thumbnail'), ('slideshow_manifest', b'Slideshow Manifest')], max_length=150),
        ),
    ]
