# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-13 01:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20200613_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmetadata',
            name='tagline',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
