# Generated by Django 3.2.5 on 2022-02-02 22:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20210707_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnode',
            name='kind',
            field=models.CharField(blank=True, choices=[('topic', 'Topic'), ('video', 'Video'), ('audio', 'Audio'), ('exercise', 'Exercise'), ('document', 'Document'), ('html5', 'HTML5 App'), ('slideshow', 'Slideshow'), ('h5p', 'H5P'), ('zim', 'Zim'), ('quiz', 'Quiz')], max_length=200),
        ),
    ]
