# Generated by Django 3.2.5 on 2022-01-27 18:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_contentnode_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
