# Generated by Django 3.2.5 on 2022-02-23 18:42
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_contentnode_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentnode",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("topic", "Topic"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("exercise", "Exercise"),
                    ("document", "Document"),
                    ("html5", "HTML5 App"),
                    ("slideshow", "Slideshow"),
                    ("h5p", "H5P"),
                    ("zim", "Zim"),
                    ("quiz", "Quiz"),
                ],
                max_length=200,
            ),
        ),
    ]
