# Generated by Django 3.2.5 on 2022-02-24 20:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0017_alter_contentnode_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentnode",
            name="accessibility_labels",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="categories",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="grade_levels",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="learner_needs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="learning_activities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="resource_types",
            field=models.TextField(blank=True, null=True),
        ),
    ]
