export const SCALE_TEXT = {
  VERY_SMALL: 'VERY_SMALL',
  SMALL: 'SMALL',
  AVERAGE: 'AVERAGE',
  LARGE: 'LARGE',
  VERY_LARGE: 'VERY_LARGE',
};

export const SCALE = [
  SCALE_TEXT.VERY_SMALL,
  SCALE_TEXT.VERY_SMALL,
  SCALE_TEXT.SMALL,
  SCALE_TEXT.SMALL,
  SCALE_TEXT.AVERAGE,
  SCALE_TEXT.AVERAGE,
  SCALE_TEXT.AVERAGE,
  SCALE_TEXT.LARGE,
  SCALE_TEXT.LARGE,
  SCALE_TEXT.VERY_LARGE,
  SCALE_TEXT.VERY_LARGE,
];

export const CHANNEL_SIZE_DIVISOR = 100000000;
