# -*- coding: utf-8 -*-
#
# Kolibri Studio documentation build configuration file, created by
# sphinx-quickstart on Mon Oct 16 16:46:14 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.

extensions = []

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Kolibri Studio'
copyright = u'2017, Learning Equality'
author = u'Learning Equality'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u''
# The full version, including alpha/beta/rc tags.
release = u'0.1.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'default'
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'


#if on_rtd:
#    os.system("sphinx-apidoc --doc-project='Python Reference' -f -o . ../kolibri ../kolibri/test ../kolibri/deployment/ ../kolibri/dist/")

if not on_rtd:  # only import and set the theme if we're building docs locally
    import sphinx_rtd_theme
    html_theme = 'sphinx_rtd_theme'
    html_theme_path = ['.', sphinx_rtd_theme.get_html_theme_path()]

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

html_logo = 'logo.png'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Approach for custom stylesheet:
# adapted from: http://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html
# and https://github.com/altair-viz/altair/pull/418/files
# https://github.com/rtfd/sphinx_rtd_theme/issues/117
def setup(app):
    # Add our custom CSS overrides
    app.add_stylesheet('theme_overrides.css')

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
# html_sidebars = {
#     '**': [
#         'about.html',
#         'navigation.html',
#         'relations.html',  # needs 'show_related': True theme option to display
#         'searchbox.html',
#         'donate.html',
#     ]
# }


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'KolibriStudiodoc'

rst_prolog = """
.. role:: raw-html(raw)
      :format: html

.. |star| replace:: :raw-html:`<span class="fa fa-star" aria-hidden="true"></span><span class="visuallyhidden">Star</span>`
.. |star-o| replace:: :raw-html:`<span class="fa fa-star-o" aria-hidden="true"></span><span class="visuallyhidden">Star</span>`
.. |copy-c| replace:: :raw-html:`<span class="fa fa-clipboard" aria-hidden="true"></span><span class="visuallyhidden">Copy to computer clipboard</span>`
.. |copy| replace:: :raw-html:`<span class="fa fa-copy" aria-hidden="true"></span><span class="visuallyhidden">Copy to Studio clipboard</span>`
.. |pencil| replace:: :raw-html:`<span class="fa fa-pencil" aria-hidden="true"></span><span class="visuallyhidden">Pencil</span>`
.. |move| replace:: :raw-html:`<span class="fa fa-arrows" aria-hidden="true"></span><span class="visuallyhidden">Move</span>`
.. |trash| replace:: :raw-html:`<span class="fa fa-trash" aria-hidden="true"></span><span class="visuallyhidden">Delete</span>`
.. |sync| replace:: :raw-html:`<span class="fa fa-refresh" aria-hidden="true"></span><span class="visuallyhidden">Sync</span>`
.. |plus| replace:: :raw-html:`<span class="fa fa-plus" aria-hidden="true"></span><span class="visuallyhidden">Plus</span>`
.. |plus-c| replace:: :raw-html:`<span class="fa fa-plus-circle" aria-hidden="true"></span><span class="visuallyhidden">Plus</span>`
.. |home| replace:: :raw-html:`<span class="fa fa-home" aria-hidden="true"></span><span class="visuallyhidden">Home</span>`
.. |close| replace:: :raw-html:`<span class="fa fa-close" aria-hidden="true"></span><span class="visuallyhidden">Close</span>`
.. |ellipsis| replace:: :raw-html:`<span class="fa fa-ellipsis-h fa-lg fa-border" aria-hidden="true"></span><span class="visuallyhidden">Ellipsis</span>`
.. |download| replace:: :raw-html:`<span class="fa fa-download" aria-hidden="true"></span><span class="visuallyhidden">Download</span>`
.. |user| replace:: :raw-html:`<span class="fa fa-user" aria-hidden="true"></span><span class="visuallyhidden">User</span>`
.. |external| replace:: :raw-html:`<span class="fa fa-external-link" aria-hidden="true"></span>`
.. |sort| replace:: :raw-html:`<span class="fa fa-sort" aria-hidden="true"></span><span class="visuallyhidden">Move up/down</span>`
"""


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'KolibriStudio.tex', u'Kolibri Studio Documentation',
     u'Learning Equality', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'kolibristudio', u'Kolibri Studio Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'KolibriStudio', u'Kolibri Studio Documentation',
     author, 'KolibriStudio', 'One line description of project.',
     'Miscellaneous'),
]



