name: Update community pull requests spreadsheet
on:
  pull_request_target:
    types: [assigned,unassigned,opened,closed,reopened]

jobs:
  call-update-spreadsheet:
    uses: learningequality/.github/.github/workflows/update-pr-spreadsheet.yml@main
    secrets:
      CONTRIBUTIONS_SPREADSHEET_ID: ${{ secrets.CONTRIBUTIONS_SPREADSHEET_ID }}
      CONTRIBUTIONS_SHEET_NAME: ${{ secrets.CONTRIBUTIONS_SHEET_NAME }}
      GH_UPLOADER_GCP_SA_CREDENTIALS: ${{ secrets.GH_UPLOADER_GCP_SA_CREDENTIALS }}
